=== sstangl/tuja-vortaro/revo/src/dtd/vokoxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--****************************************************
          KADRA STRUKTURO DE VORTARO
********************************************************-->

<!-- [vortaro] Radiko de la strukturarbo de vortaro. La elemento ampleksas
la tutan vortaron.<p>
Ĝi entenas aŭ prologon, precipan parton kaj epilogon aŭ plurajn
artikolojn. Prologo kaj epilogo estas nedevigaj. La ebleco de rekta
enteno de artikolo ne estas destinita por kompletaj vortaroj, sed por
eltiroj aŭ unuopa artikolo.-->

<!ELEMENT vortaro ((prologo?,precipa-parto,epilogo?)|art+)>

<!-- [prologo] Prologo de la vortaro. Ĝi povas enteni la titolo(j)n 
kaj aŭtoro(j)n de la vortaro kaj aliajn tekstojn.-->

<!ELEMENT prologo (#PCDATA|titolo|autoro|alineo)*>

<!-- [epilogo] Epilogo de la vortaro. Ĝia strukturo momente ne estas
specifita. Ĝi povas enhavi iun tekston.-->

<!ELEMENT epilogo (#PCDATA|alineo)*>

<!-- [titolo] Titolo de la vortaro. Ĝi estas entenata en la 
prologo. Pluraj titoloj estas permesitaj.-->

<!ELEMENT titolo (#PCDATA)>

<!-- [autoro] Indiko de aŭtoro(j) de la vortaro. 
Ĝi estas enhavata en la prologo kaj povas okazi tie plurfoje.-->

<!ELEMENT autoro (#PCDATA)>

<!-- [alineo] unuopa alineo en la prologo-teksto -->

<!ELEMENT alineo (#PCDATA|url)*>

<!-- [precipa-parto] Precipa parto de la vortaro. Ĝi enhavas rekte ĉiujn
artikolojn aŭ sekciojn aŭ partojn. 
Diversaj partoj povas dividi diversajn lingvojn de la kapvortoj.
Sekcioj grupigas vortojn komencighantajn je sama litero.
-->

<!ELEMENT precipa-parto (parto+|sekcio+|art+)>

<!-- [parto] Vortaroparto. Ĝi estas entenata en la precipa parto. Parto normale
prezentas unu lingvon en plurlingva vortaro aŭ lingvodirekton en
dulingva vortaro. Ĝia atributo <dfn>lng</dfn> indikas la lingvon de
la kapvortoj en la parto.-->

<!ELEMENT parto (sekcio+|art+)>
<!ATTLIST parto
	lng CDATA #IMPLIED
>

<!-- [sekcio] Sekcio en vortaro. Ĝi estas entenata en la precipa parto aŭ en
parto de ĝi kaj normale entenas ĉiujn artikolojn, kies kapvorto
komenciĝas je sama litero. La atributo <dfn>lit</dfn> indikas tiun
komencliteron.-->

<!ELEMENT sekcio (art+)>
<!ATTLIST sekcio
	lit CDATA #IMPLIED
>

<!-- ******************************************************
             STRUKTURO DE ARTIKOLO
***********************************************************-->

<!-- [%priskribaj-elementoj] La unuo <dfn>priskribaj-elementoj</dfn> 
listigas ĉiujn strukturilojn, kiuj priskribas kapvorton aŭ unuopan 
sencon de ĝi. Ĉar ili povas okazi multloke en la strukturo de 
artikolo estas avantaĝe difini tiun ĉi unuon.-->

<!-- priskribaj elementoj -->
<!ENTITY % priskribaj-elementoj 
  "fnt|gra|uzo|dif|ekz|rim|ref|refgrp|trd|trdgrp|bld|adm|url|mlg|lstref|tezrad">

<!-- [%tekst-stiloj] La unuo <dfn>tekst-stiloj</dfn> 
listigas ĉiujn strukturilojn, kiuj donas stilon al tekstoparto,
ekz. emfazita, citilita, altigita aŭ malaltigita teksto.
Aliaj elementoj klarigo kaj tildo kaj sencreferenco same povas esti
multloke, do ankaŭ ili estas listigitaj tie ĉi. -->

<!-- tekst-stiloj -->
<!ENTITY % tekst-stiloj "tld|sncref|klr|em|sup|sub|ctl|frm">

<!-- [art] Unuopa artikolo de la vortaro. Ĝi povas okazi en
<dfn>vortaro</dfn> (se ne ekzistas precipa-parto),
<dfn>precipa-parto</dfn>, <dfn>parto</dfn> aŭ <dfn>sekcio</dfn>. Tio
dependas de la konkreta strukturo de la vortaro. Ĉiu artikolo
entenas unue kapvorton kaj poste aŭ priskribajn elementojn aŭ plurajn
derivaĵojn aŭ plurajn sencojn de la kapvorto aŭ subartikolojn. -->

<!ELEMENT art (kap,(subart|drv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST art
	mrk CDATA #REQUIRED
>

<!-- [subart] Subartikolo. Ĝi povas okazi en <dfn>artikolo</dfn>,
se la signifoj de vorto (ofte ĉe prepozicioj kaj afiksoj) estas
tre diversaj. -->

<!ELEMENT subart (drv|snc|%priskribaj-elementoj;)*>

<!-- [drv] Derivaĵo ene de artikolo. Unu artikolo povas priskribi plurajn
derivaĵojn de la kapvorto. Derivaĵo komenciĝas ja kapvorto kaj
priskribaj elementoj pri ĝi aŭ el unu aŭ pluraj sencoj aŭ el unu aŭ
pluraj subdividoj <dfn>subdrv</dfn>.-->

<!ELEMENT drv (kap,(subdrv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST drv
	mrk ID #REQUIRED
>

<!-- [var] variaĵo de la vorto, ekz. meĥaniko - mekaniko, pomarbo -
pomujo. Ĝi povas enhavi fontindikon k.s., sed ankaŭ rimarkojn 
kaj ekzemplojn, sed ĝi ne havas propran difinon. Ĝi aperas ene
de kapvorto, ĉar ĝi ja estas ĝia variaĵo.
-->

<!ELEMENT var (kap,(uzo|klr|ekz|rim)*)>

<!-- [subdrv] Subderivaĵo. Ĝi grupigas plurajn proksimajn sencojn, se la
priskribita vorto havas tre multajn sencojn. Tio povas
rezulti en pli klara strukturo de la artikolo. La subdividaĵoj
estas nombrataj per A), B), ... -->

<!ELEMENT subdrv (snc|%priskribaj-elementoj;)*>

<!-- [snc] Senco de unuopa vorto en artikolo. Komparu la latinajn ciferojn en
la artikoloj de PIV. Per mrk oni povas referenci sencon de alie. Per ref oni
referencas al alia senco samartikola (uzata en malmultaj longaj artikoloj, ekz.
"al". Per num la senco ricevas numeron. Atentu, ke future simbolaj nomoj por
la sencoj estos perferataj kaj do numerado okazas automate ignorante la atributon
num. -->

<!ELEMENT snc (subsnc|%priskribaj-elementoj;)*>
<!ATTLIST snc
	mrk ID #IMPLIED
        num CDATA #IMPLIED
	ref CDATA #IMPLIED
>

<!-- [subsnc] Subsenco ene de senco. Ĝi redonas subtilaĵojn ene de unu senco.
Ili estas nombrataj per a), b), ... -->

<!ELEMENT subsnc (%priskribaj-elementoj;)*>
<!ATTLIST subsnc
	mrk ID #IMPLIED
        ref CDATA #IMPLIED
>

<!-- [sncref] Referenco al alia senco. Tiu elemento estas anstatauigata
 per la numero de la referencita senco. Vi povas forlasi la atributon 
 ref, se ekzistas parenca elemento ref, kies atributo cel montras al la
 referencita senco.
-->

<!ELEMENT sncref EMPTY>
<!ATTLIST sncref
       ref CDATA #IMPLIED
>

<!-- ************************************************
            STRUKTUROJ DE DETALAJ ELEMENTOJ
*****************************************************-->

<!-- [kap] kapvorto okazas en du kuntekstoj - komence de artikolo
kaj komence de derivaĵo, en la unua kazo ĝi signas radikon
en la dua kazo ĝi konsistas el iuj literoj kaj eble tildo
refencanta al la kapvorto, krome en la kapvorto povas okazi
fontindiko.
-->

<!ELEMENT kap (#PCDATA|rad|ofc|fnt|tld|var)*>

<!-- [rad] Radiko de kapvorto. Ĝi estas bezonata por anstaŭigo
de tildoj. Sekve la "radiko" de afiksoj kaj finaĵoj estu
ili mem, sen la streketoj antaŭe aŭ malantaŭe.-->

<!ELEMENT rad (#PCDATA)>

<!-- [ofc] Oficialeco de la kapvorto/derivajho, 
  povas esti *, 1, ..., 8 kiel en PIV -->

<!ELEMENT ofc (#PCDATA)>

<!-- [fnt] Fonto enhavas informojn pri autoro, verko, trovloko
au aliajn informojn.-->

<!ELEMENT fnt (#PCDATA|bib|aut|vrk|lok|url)*>

<!-- [gra] kiel grammatikaj informoj momente estas permesataj
nur indiko de la vortspeco.-->

<!ELEMENT gra (#PCDATA|vspec)*>

<!-- [vspec] Vortspeco. Ekz. subst. por substantivo; tr./ntr.
por transitivaj kaj netransitivaj verboj ktp.-->

<!ELEMENT vspec (#PCDATA)>

<!-- [uzo] La uzo povas esti stilo, fako, regiono aŭ alia klarigo,
kiel estas uzata la vorto au termino. Por la fakoj kaj stiloj uzu
unu el la aliloke listigitaj mallongigoj.
-->

<!ELEMENT uzo (#PCDATA|tld)*>
<!ATTLIST uzo
	tip (fak|reg|klr|stl) #IMPLIED
>

<!-- [dif] Difino estas la frazo difinanta la vorton, sencon aŭ
subsencon. Ĝi povas esti ankaŭ en alia(j) lingvo(j) ol la vorto
mem. La lingvon indikas la atributo <dfn>lng</dfn>.
-->

<!ELEMENT dif (#PCDATA|trd|trdgrp|ref|refgrp|ekz|snc|%tekst-stiloj;)*>
<!ATTLIST dif
	lng CDATA #IMPLIED
>

<!-- [ekz] Ekzemplo konsistas el ekzemplofrazo,
klarigoj kaj fonto.
-->

<!ELEMENT ekz (#PCDATA|fnt|uzo|ref|refgrp|ind|trd|trdgrp|%tekst-stiloj;)*>
<!ATTLIST ekz
	mrk ID #IMPLIED
>

<!-- [rim] Rimarko povas enhavi iujn indikojn pri la vorto aŭ
senco, krome referencojn, ekzemplojn, emfazitajn partojn.
-->
<!ELEMENT rim (#PCDATA|ref|refgrp|ekz|aut|fnt|%tekst-stiloj;)*>
<!ATTLIST rim
        num CDATA #IMPLIED
	mrk ID #IMPLIED
> 

<!-- [refgrp] Referencgrupo grupigas plurajn samtipajn
referencojn. La tipon indikas la atributo <dfn>tip</dfn>.
Tiukaze ne uzu la atributon <dfn>tip</dfn> en la subelementoj
<dfn>ref</dfn>!
-->

<!ELEMENT refgrp (#PCDATA|ref)*>
<!ATTLIST refgrp
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) "vid"
>

<!-- [ref] Referenco montras al alia, simil- aŭ alisignifa vorto,
oni povas distingi diversajn rilattipon al la
referencita vorto. La enhavo de la referenco estas tio, kio
aperas en la legebla teksto. La referencitan vorton mem
oni difinas per la atributo "cel". La celon oni plej
bone difinas per: radiko.derivaĵo.difino, oni povas uzi
la numeron de la difino au derivaĵo. Plej bone oni
generas la markojn (t.e. la eblaj celoj de referenco)
aŭtomate por minimumigi erarojn.
La atributoj "lst" kaj "val" servas por referenci al vortlisto (tip="lst"),
ekz. monatoj. Se temas pri ordigita listo, vi povas indiki valoron per "val",
ekz. "3" che la monato marto.
-->

<!ELEMENT ref (#PCDATA|tld|klr|sncref)*>
<!ATTLIST ref
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) #IMPLIED
	cel CDATA #REQUIRED
        lst CDATA #IMPLIED
	val CDATA #IMPLIED
>

<!-- [tez] NE PLU UZU! Tezaŭra nodo. Ĝi permesas referenci al tio, same kiel
 al kap kaj mem povas referenci al alia nodo.
-->
<!ELEMENT tez (#PCDATA|tld|klr|ref|refgrp)*>
<!ATTLIST tez
        mrk CDATA #REQUIRED
        tip (super|malprt|listo) #IMPLIED
	cel CDATA #REQUIRED
>

<!-- [lstref] Referenco al vortlisto el artikolo.
-->
<!ELEMENT lstref (#PCDATA|tld|klr)*>
<!ATTLIST lstref
        lst CDATA #REQUIRED
>

<!-- [tezrad] Tezaŭraradiko. La kapvorto aperas en la enir-listo
de la tezaŭro. Se vi uzas la atributon fak, ĝi aperas en la 
struktura enirlisto de la fako -->
<!ELEMENT tezrad EMPTY>
<!ATTLIST tezrad
        fak CDATA #IMPLIED
>

<!-- [trdgrp] Tradukgrupo kunigas diversajn tradukojn de
sama lingvo.
-->
<!ELEMENT trdgrp (#PCDATA|trd)*>
<!ATTLIST trdgrp
	lng CDATA #REQUIRED
>

<!-- [trd] Traduko kosistas el traduka vorto aŭ frazo
kaj klarigoj, poste povos sekvi aliaj elementoj.
-->
<!ELEMENT trd (#PCDATA|klr|ind|mll|ofc)*>
<!ATTLIST trd
	lng CDATA #IMPLIED
>

<!-- [ind] Parto de traduko, kiu liveras la kapvorton en la
indekso, do &lt;trd&gt;sich &lt;ind&gt;bem&uuml;hen&lt;/ind&gt;&lt;/trd&gt;
aperas sub bem&uuml;hen. Aŭ parto de ekzemplo aŭ bildpriskribo, al
kiu rilatas internaj tradukoj ktp.
-->
<!ELEMENT ind (#PCDATA|tld|klr|mll)*>

<!ELEMENT mll (#PCDATA|tld|klr|ind)*>
<!ATTLIST mll
        tip (kom|mez|fin) #IMPLIED
>

<!-- [bld] Bildo povas ilustri iun vorton aŭ sencon. Per la
atributo <dfn>lok</dfn> ĝi
referencas al ekstera dosiero, kiu entenas la bildon.
Per <dfn>alt</dfn> kaj <dfn>lrg</dfn> vi povas doni fiksan formaton.
Per <dfn>tip</dfn> vi donas tipon de la bildo, t.e. <dfn>img</dfn>
por JPEG, GIF, PNG-bildo, <dfn>svg</dfn> por SVG-vektorgrafiko.
-->
<!ELEMENT bld (#PCDATA|tld|klr|fnt|ind|trd|trdgrp)*>
<!ATTLIST bld
	lok CDATA #REQUIRED
	mrk ID #IMPLIED
	tip (img|svg) "img"
	alt CDATA #IMPLIED 
	lrg CDATA #IMPLIED
>

<!-- [adm] Administraj informoj estu por redaktado. Ili povus
enhavi informojn pri kreodato, ŝanĝdato, aŭtoro, eraroj kaj
plibonigproponoj pri artikolo. Ĝia strukturo ankoraŭ estas
diskutatebla.
-->
<!ELEMENT adm (#PCDATA|aut)*>

<!-- [tld] Tildo rilatas al la radiko, donita en la kapvorto
ĝi ne bezonas enhavon. La atributo <dfn>lit</dfn> indikas alian
komencliteron ol havas la radiko. Grava por majuskligo kaj
minuskligo.
-->
<!ELEMENT tld EMPTY>
<!ATTLIST tld
            lit CDATA #IMPLIED>       

<!-- [klr] Klarigo pri vorto, difino, ekzemplo ktp.-->
<!ELEMENT klr (#PCDATA|trd|trdgrp|ekz|ref|refgrp|%tekst-stiloj;)*>
<!ATTLIST klr
            tip (ind|amb) #IMPLIED>

<!-- [bib] Bibliografia indiko por fonto, estas mallongigo el
listo de difinitaj bibliografieroj kaj anstataŭas verko- kaj aŭtoroindikon
en la fontoj.
-->
<!ELEMENT bib (#PCDATA)*>

<!-- [vrk] Verko, en kiu troviĝas citita frazo aŭ vorto -->
<!ELEMENT vrk (#PCDATA|url)*>

<!-- [lok] Loko, kie troviĝas citita frazo aŭ vorto en verko -->
<!ELEMENT lok (#PCDATA|url)*>

<!-- [aut] Aŭtoro de citita frazo aŭ verko -->
<!ELEMENT aut (#PCDATA)>

<!-- [frm] Matematika au kemia formulo -->
<!ELEMENT frm (#PCDATA|sup|sub|g|k)*>

<!-- [g] Grasa parto de formulo, ekz. vektoro, matrico k.s.,
  bv. uzi nur en frm -->
<!ELEMENT g (#PCDATA)*>

<!-- [k] Kursiva parto de formulo, ekz. variablo k.s.,
  bv. uzi nur en frm -->
<!ELEMENT k (#PCDATA)*>

<!-- [em] Emfazo. Normale grase skribata vortoj.-->
<!ELEMENT em (#PCDATA|tld)*>

<!-- [sup] altigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sup (#PCDATA|g|k)*>

<!-- [sub] malaltigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sub (#PCDATA|g|k)*>

<!-- [ctl] citilita teksto, ekz. memindika uzo de vorto -->
<!ELEMENT ctl (#PCDATA|tld|em|frm)*>

<!-- [url] Referenco al iu ekstera dosiero. En la HTML-versio de vortaro
tio fariĝas &lt;a href=...&gt; Anstataŭ la TTT-ejo prefere uzu
la alinomojn difinitajn en la DTD, ĉar alikaze la referencoj tro
ofte malvalidiĝus. -->

<!ELEMENT url (#PCDATA)>
<!ATTLIST url 
          ref CDATA #IMPLIED>

<!-- [mlg] mallongigo de la kapvorto, ekz. che nomoj de organizajhoj. 
Per "kod" vi povas indiki devenon de la mallongigo, ekz. ISO-3166 ĉe landokodoj -->

<!ELEMENT mlg (#PCDATA)>
<!ATTLIST mlg
          kod CDATA #IMPLIED>




<!-- *************************************************
                   LITEROJ
******************************************************
-->

<!ENTITY % signoj SYSTEM "../dtd/vokosgn.dtd">
%signoj;

<!-- ************************************************
                   MALLONGIGOJ
*****************************************************
-->

<!ENTITY % mallongigoj SYSTEM "../dtd/vokomll.dtd">
%mallongigoj;

<!-- *************************************************
                   URLoj
******************************************************
-->

<!ENTITY % urloj SYSTEM "../dtd/vokourl.dtd">
%urloj;

=== sstangl/tuja-vortaro/revo/src/xml/intim.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: intim.xml,v 1.21 2015/12/30 21:10:16 revo Exp $">
<kap>
  <ofc>*</ofc>
  <rad>intim</rad>/a <fnt><bib>PV</bib></fnt>
</kap>
<drv mrk="intim.0a">
  <kap><ofc>*</ofc><tld/>a</kap>
  <snc mrk="intim.0a.sento">
    <dif>
      Karakterizata per profunde komunaj sentoj kaj plena konfido kaj
      sen&gcirc;eneco:
      <ekz>
        <tld/>a amiko;
      </ekz>
      <ekz>
        vivi kun iu en <tld/>a amikeco
        <fnt><bib>PrV</bib></fnt>
      </ekz>
      <ekz>
        <tld/>aj interrilatoj;
      </ekz>
      <ekz>
        <tld/>a interparolado;
      </ekz>
      <ekz>
        <uzo tip="stl">FIG</uzo>
        Esperanto estas al li same <tld/>a <klr>(malfremda,
        sen&gcirc;ene uzata)</klr> kiel la gepatra lingvo.
      </ekz>
    </dif>
    <refgrp tip="vid">
      <ref cel="famili1.0a">familiara</ref>,
      <ref cel="hejm.0eca">hejmeca</ref>.
    </refgrp>
    <trdgrp lng="de">
      <trd>intim</trd>,
      <trd>vertraut</trd>,
      <trd>innig</trd>
    </trdgrp>
    <trdgrp lng="hu">
      <trd>intim</trd>,
      <trd>bens&odblac;s&eacute;ges</trd>,
      <trd>meghitt</trd>
    </trdgrp>
    <trd lng="nl">intiem</trd>
    <trd lng="pt">familiar</trd>
    <trdgrp lng="ru">
      <trd>&c_i;&c_n;&c_t;&c_i;&c_m;&c_n;&c_y;&c_j;</trd>,
      <trd>&c_b;&c_l;&c_i;&c_z;&c_k;&c_i;&c_j;</trd>,
      <trd>&c_z;&c_a;&c_d;&c_u;&c_sh;&c_je;&c_v;&c_n;&c_y;&c_j;</trd>
    </trdgrp>
  </snc>
  <snc mrk="intim.0a.nepublika">
    <dif>
      Ekzistanta tute interne; ne aperanta ekstere; nepublika:
      <ekz>
        <tld/>aj sentoj, konvinkoj;
      </ekz>
      <ekz>
        la <tld/>a vivo;
      </ekz>
      <ekz>
        <tld/>aj aferoj;
      </ekz>
      <ekz>
        <tld/>a <klr>(senceremonia)</klr> vizito, festo.
      </ekz>
    </dif>
    <trdgrp lng="de">
      <trd>intim</trd>,
      <trd>privat</trd>
    </trdgrp>
    <trd lng="hu">bens&odblac;</trd>
    <trdgrp lng="pt">
     <trd>&iacute;ntimo</trd>, 
     <trd>particular</trd> 
    </trdgrp>
    <trdgrp lng="ru">
      <trd>&c_i;&c_n;&c_t;&c_i;&c_m;&c_n;&c_y;&c_j;</trd>,
      <trd>&c_l;&c_i;&c_ch;&c_n;&c_y;&c_j;</trd>,
      <trd>&c_p;&c_r;&c_i;&c_v;&c_a;&c_t;&c_n;&c_y;&c_j;</trd>
    </trdgrp>
  </snc>
  <trdgrp lng="cs">
    <trd>d&uring;v&ecaron;rn&yacute;</trd>,
    <trd>d&uring;v&ecaron;rn&yacute;</trd>,
    <trd>intimn&iacute;</trd>,
    <trd>&uacute;tuln&yacute;</trd>
  </trdgrp>
  <trd lng="es">&iacute;ntimo</trd>
  <trdgrp lng="fr">
    <trd>intime<klr tip="ind"> (adj.)</klr></trd>,
    <trd>priv&eacute;<klr tip="ind"> (intime)</klr></trd>,
    <trd>secret<klr tip="ind"> (intime)</klr></trd>,
    <trd>profond<klr tip="ind"> (intime)</klr></trd>
  </trdgrp>
  <trdgrp lng="id">
    <trd>akrab</trd>,
    <trd>intim</trd>
  </trdgrp>
  <trdgrp lng="sk">
    <trd>d&ocirc;vern&yacute;</trd>,
    <trd>int&iacute;mny</trd>,
    <trd>&uacute;zky <klr>(vz&tcaron;ah)</klr></trd>
  </trdgrp>
</drv>

<drv mrk="intim.0eco">
  <kap><tld/>eco</kap>
  <snc mrk="intim.0eco.KOMUNE">
    <dif>
      Eco de io <tld/>a:
      <ekz>
        vivi en granda <tld/>eco kun iu;
      </ekz>
      <ekz>
        <tld/>ece briletis la teleretoj<fnt>Z</fnt>.
      </ekz>
    </dif>
  </snc>
  <trdgrp lng="cs">
    <trd>intimita</trd>,
    <trd>intimnost</trd>
  </trdgrp>
  <trdgrp lng="de">
    <trd>Intimit&auml;t</trd>,
    <trd>Vertrautheit</trd>,
    <trd>Innigkeit</trd>
  </trdgrp>
  <trd lng="es">intimidad</trd>
  <trd lng="fr">intimit&eacute;</trd>
  <trdgrp lng="hu">
    <trd>intimit&aacute;s</trd>,
    <trd>bens&odblac;s&eacute;gess&eacute;g</trd>,
    <trd>meghitts&eacute;g</trd>
  </trdgrp>
  <trd lng="nl">intimiteit</trd>
  <trd lng="pt">intimidade</trd>
  <trdgrp lng="ru">
    <trd>&c_i;&c_n;&c_t;&c_i;&c_m;&c_n;&c_o;&c_s;&c_t;&c_mol;</trd>,
    <trd>&c_b;&c_l;&c_i;&c_z;&c_o;&c_s;&c_t;&c_mol;</trd>,
    <trd>&c_z;&c_a;&c_d;&c_u;&c_sh;&c_je;&c_v;&c_n;&c_o;&c_s;&c_t;&c_mol;</trd>,
    <trd>&c_s;&c_je;&c_r;&c_d;&c_je;&c_ch;&c_n;&c_o;&c_s;&c_t;&c_mol;</trd>
  </trdgrp>
  <trd lng="sk">d&ocirc;vernos&tcaron;</trd>
</drv>

<drv mrk="intim.0ismo">
  <kap><tld/>ismo</kap>
  <snc mrk="intim.0ismo.BELA">
    <uzo tip="fak">BELA</uzo>
    <uzo tip="fak">BELE</uzo>
    <dif>
      Prefero por temoj kaj esprimoj <tld/>aj,
      mal<ref tip="ant" cel="patos.0o.BELA">patosaj</ref>:
      <ekz>
        lirikaj esprimoj <tld/>ismaj <klr>...</klr> fluas serene kaj 
        simple kiel klara akvo el fonto
        <fnt>
          <aut>A. M. Botella</aut>,
          <vrk><url
          ref="https://sites.google.com/site/zaragozafrateco/antonio-marco/beletraj-pagoj/antonio-machado">
          La poeto de la intimismaj kolokvoj</url></vrk>,
          <lok>2000</lok>
        </fnt>.
      </ekz>
    </dif>
    <trd lng="fr">intimisme</trd>
  </snc>
</drv>

<drv mrk="intim.0ulo">
  <kap><tld/>ulo</kap>
  <snc mrk="intim.0ulo.KOMUNE">
    <dif>
      Persono, alligata al alia per reciprokaj sentoj kaj plena
      <ref cel="konfid.0o">konfido</ref>.
    </dif>
    <refgrp tip="vid">
      <ref cel="konfid1">konfidenculo</ref>.
    </refgrp>
  </snc>
  <trd lng="cs">d&uring;v&ecaron;rn&iacute;k</trd>
  <trdgrp lng="de">
    <trd>Intimus</trd>,
    <trd>Vertraute</trd>,
    <trd>Vertrauter</trd>
  </trdgrp>
  <trd lng="es">amigo <ind>&iacute;ntimo</ind></trd>
  <trdgrp lng="fr">
    <trd>intime<klr tip="ind"> (subst.)</klr></trd>,
    <trd>proche<klr tip="ind"> (subst.)</klr></trd>
  </trdgrp>
  <trdgrp lng="hu">
    <trd>meghitt bar&aacute;t</trd>,
    <trd>bizalmas<klr tip="amb">(a vkinek)</klr></trd>
  </trdgrp>
  <trd lng="nl">intieme vriend</trd>
  <trd lng="pt">pessoa <ind>&iacute;ntima</ind></trd>
  <trd lng="sk">d&ocirc;vern&iacute;k</trd>
</drv>

<drv mrk="intim.mal0a">
  <kap>mal<tld/>a</kap>
  <snc mrk="intim.mal0a.KOMUNE">
    <dif>
      Ekstere videbla, publika,
      <ref tip="vid" cel="fremd.0a.aliula">fremda<sncref/></ref>:
      <ekz>
        la &ccirc;ambro &scirc;ajnis vasta, kruda kaj mal<tld/>a
        <fnt>
          <aut>Hasegawa T.</aut>,
          <vrk><url
          ref="http://wikilivres.ca/wiki/En_%C4%88inio_Batalanta">
          En &Ccirc;inio Batalanta</url></vrk>, 
          <lok>1954</lok>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="fr">impersonnel</trd>
  <trd lng="id">impersonal</trd>
</drv>
</art>
<!--
$Log: intim.xml,v $
Revision 1.21  2015/12/30 21:10:16  revo
Jeromo Vasxe: + ~ismo

Revision 1.20  2015/07/04 08:37:36  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.19  2015/06/29 16:33:16  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.18  2014/06/03 15:10:25  revo
Eko Nur Syah Hidayat: +id

Revision 1.17  2012/09/19 08:10:12  revo
Jeromo Vasxe: + mal~a

Revision 1.16  2010/04/01 16:30:28  revo
Bart Demeyere: +mrkoj

Revision 1.15  2005/12/05 17:31:23  revo
Luiz Portella: +trd pt

Revision 1.14  2004/09/06 16:36:36  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/bragx.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: bragx.xml,v 1.14 2009/03/24 17:30:29 revo Exp $">
<kap>
  <rad>bra&gcirc;</rad>/o
</kap>

<drv mrk="bragx.0o">
  <kap><tld/>o</kap>
  <snc>
    <dif>
      Ardaj ligno- a&ubreve; karbopecoj, jam duone konsumitaj kaj ne
      plu &jcirc;etantaj flamon:
      <ekz>
        fajrobrigadistoj alvenas kiam &ccirc;io forbrulis,
        &gcirc;ustatempe por
        observi la subcindrajn <tld/>ojn<fnt><aut>Hamza
        Baksi&cacute;</aut>:
        <vrk>La fino de la mondo komenci&gcirc;as en Sarajevo</vrk>,
        <bib>Monato</bib><lok>jaro 1993a, numero 10a, p. 8a</lok></fnt>.
      </ekz>
    </dif>
    <refgrp tip="sin">
      <ref cel="karb.0eto">karbeto</ref>,
      <ref cel="ard.karb0ajxo">karbarda&jcirc;o</ref>.
    </refgrp>
    <trd lng="de">Glut</trd>
    <trd lng="fr">braise</trd>
    <trd lng="hu">par&aacute;zs</trd>
    <trd lng="pl">w&eogonek;gle</trd>
    <trdgrp lng="ru">
      <trd>&c_r;&c_a;&c_s;&c_k;&c_a;&c_l;&c_jo;&c_n;&c_n;&c_y;&c_je;
      &c_u;&c_g;&c_l;&c_i;</trd>,
      <trd>&c_zh;&c_a;&c_r;</trd>
    </trdgrp>
  </snc>
  <snc>
    <dif>
      Tiaj samaj pecoj, estingitaj anta&ubreve; plena konsumi&gcirc;o
      kaj
      uzataj kiel <ref tip="super"
      cel="brul.0igajxo">bruliga&jcirc;o</ref>.
    </dif>
    <refgrp tip="sin">
      <ref cel="karb.0eto">karbeto</ref>,
      <ref cel="karb.ligno0o">lignokarbo</ref>.
    </refgrp>
    <trd lng="de">Holzkohle</trd>
    <trdgrp lng="fr">
      <trd>charbon de bois</trd>
    </trdgrp>
    <trd lng="hu">fasz&eacute;n</trd>    
    <trd lng="pl">w&eogonek;giel drzewny</trd>
    <trdgrp lng="ru">
      <trd>&c_u;&c_g;&c_l;&c_i;</trd>,
      <trd>&c_g;&c_o;&c_l;&c_o;&c_v;&c_je;&c_sh;&c_k;&c_i;</trd>
    </trdgrp>
  </snc>
  <trdgrp lng="be">
    <trd>&c_v;&c_u;&c_g;&c_a;&c_l;&c_mol;</trd>,
    <trd>&c_v;&c_u;&c_g;&c_o;&c_l;&c_mol;&c_l;&c_je;</trd>,
    <trd>&c_g;&c_a;&c_l;&c_a;&c_v;&c_je;&c_sh;&c_k;&c_ib;</trd>,
    <trd>&c_zh;&c_a;&c_r;</trd>
  </trdgrp>
  <trd lng="es">brasa</trd>
</drv>

<drv mrk="bragx.0ujo">
  <kap><tld/>ujo</kap>
  <snc>
    <dif>
      Metala a&jcirc;ura <ref tip="super" cel="fajr.0ujo">fajrujo</ref>,
      ofte portebla kaj metita sur piedo, uzata por teni ardajn
      <tld/>ojn
      kaj servi kiel <ref tip="super" cel="hejt">hejtilo</ref>.
    </dif>
  </snc>
  <trdgrp lng="be">
    <trd>&c_a;&c_ch;&c_a;&c_g;</trd>,
    <trd>&c_zh;&c_a;&c_r;&c_o;&c_w;&c_n;&c_ja;</trd>
  </trdgrp>
  <trd lng="de">Brasero</trd>
  <trd lng="es">brasero</trd>
  <trd lng="fr">brasero</trd>
  <trdgrp lng="hu">
    <trd>par&aacute;zs&uuml;st</trd>,
    <trd>mang&aacute;l</trd>
  </trdgrp>
  <trdgrp lng="ru">
    <trd>&c_o;&c_ch;&c_a;&c_g;</trd>,
    <trd>&c_zh;&c_a;&c_r;&c_o;&c_v;&c_n;&c_ja;</trd>
  </trdgrp>
</drv>
</art>
<!--
$Log: bragx.xml,v $
Revision 1.14  2009/03/24 17:30:29  revo
Sebastian Cyprych: +trd pl

Revision 1.13  2007/06/14 16:31:32  revo
Wieland Pusch: +trd de

Revision 1.12  2005/07/28 19:54:02  revo
Jozefo Horvath: +trd hu

Revision 1.11  2005/06/27 19:21:02  revo
Yury Finkel: +trd ru, -adm

Revision 1.10  2004/11/16 17:31:34  revo
Zmicier Lapcionak: + trd be

Revision 1.9  2002/10/02 07:34:09  revo
Jeromo Vasxe: + ekz, + 1 trd fr

Revision 1.8 2002/05/17 16:32:29 revo
Alejandro Mejia Greene: ald 2 his trd

Revision 1.7 2002/03/20 17:34:54 revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/gxinz.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: gxinz.xml,v 1.15 2015/01/29 04:10:52 revo Exp $">
<kap>
  <rad>&gcirc;inz</rad>/o
</kap>
<drv mrk="gxinz.0o">
  <kap><tld/>o</kap>
  <uzo tip="fak">TEKS</uzo>
  <snc mrk="gxinz.0o.TEKS">
    <dif>
      <ref tip="super" cel="pantal.0o">Pantalono</ref>
      de okcident-usona origino, el
      <ref tip="prt" cel="drelik.0o">dreliko</ref>, ofte blua:
      <ekz>
        sur la planko ku&scirc;is malnovaj gazetoj kaj kovertoj, sur
        la ununura se&gcirc;o ies <tld/>o, &scirc;trumpetoj, mamzono
        <fnt>
        <aut>Saliko</aut>, <vrk>En fremda lando</vrk>. <bib>Monato</bib>
        </fnt>;
      </ekz>
      <ekz>
        li portis nur grizan someran jakon kaj <tld/>on
        <fnt>
        <aut>PEJNO Simono</aut>, <vrk>La profeta kurso</vrk>.
        <bib>Monato</bib>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="be">&c_d;&c_zh;&c_y;&c_n;&c_s;&c_y;</trd>
  <trdgrp lng="bg">
    <trd>&c_d;&c_malmol;&c_n;&c_k;&c_i;</trd>,
    <trd>&c_d;&c_zh;&c_i;&c_n;&c_s;&c_i;</trd>
  </trdgrp>
  <trdgrp lng="de">
    <trd>Jeans</trd>,
    <trd>Nietenhose</trd>
  </trdgrp>
  <trd lng="cs">d&zcaron;in(s)y</trd>
  <trd lng="en">jeans</trd>
  <trdgrp lng="es">
    <trd>(pantalones) <ind>vaqueros</ind></trd>,
    <trd>jeans</trd>,
    <trd>pantal&oacute;n de <ind>mezclilla</ind></trd>
  </trdgrp>
  <trd lng="hu">farmernadr&aacute;g</trd>
  <trdgrp lng="id">
    <trd>jeans</trd>,
    <trd>jins</trd>
  </trdgrp>
  <trd lng="it">blue-jeans</trd>
  <trd lng="fr">jeans</trd>
  <trd lng="nl">jeans</trd>
  <trd lng="pl">d&zdot;insy</trd>
  <trd lng="pt">jeans</trd>
  <trd lng="ru">&c_d;&c_zh;&c_i;&c_n;&c_s;&c_y;</trd>
</drv>
</art>
<!--
$Log: gxinz.xml,v $
Revision 1.15  2015/01/29 04:10:52  revo
Eko Nur Syah Hidayat: +trd id

Revision 1.14  2011/09/17 22:10:10  revo
Wieland Pusch: +trd bg

Revision 1.13  2005/12/24 17:31:02  revo
Jeromo Vasxe: + mrk

Revision 1.12 2005/12/12 17:31:21 revo
Sergio Pokrovskij: +ekz

Revision 1.11 2004/01/10 17:32:12 revo
Dmitri Gabinski: +trd be

Revision 1.10 2003/07/13 16:31:38 revo
Sergio Pokrovskij: +trd=cs,pl

Revision 1.9 2003/01/25 17:31:15 revo
Marco Trevisan Herraz: +trd it, alia trd hi

Revision 1.8 2002/07/09 17:35:03 revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/neuxrodegener.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: neuxrodegener.xml,v 1.1 2014/05/01 08:10:28 revo Exp $">
<kap>
  <rad>ne&ubreve;rodegener</rad>/o
</kap>
<drv mrk="neuxrodegener.0o">
  <kap><tld/>o</kap>
  <snc mrk="neuxrodegener.0o.MED">
    <uzo tip="fak">MED</uzo>
    <dif>
      Malboni&gcirc;o de funkciado de la nervosistemo
      pro degenero de ne&ubreve;ronoj, ka&ubreve;zanta diversajn
      malsanojn:
      <ekz>
        <tld/>a malsano <ctl>Morbus Huntington</ctl>
        <fnt>
          <aut>A. Oberndorfer</aut>,
          <vrk><url
          ref="http://esperantaretradio.blogspot.com/2014/04/grava-molekulo-por-purigado-de-celoj.html">
          Grava molekulo por purigado de &ccirc;eloj</url></vrk>,
          <lok>Esperanta Retradio, 2014-04-07</lok>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="en">neurodegeneration</trd>
  <trd lng="fr">neurod&eacute;g&eacute;n&eacute;rescence</trd>
</drv>
</art>

<!--
$Log: neuxrodegener.xml,v $
Revision 1.1  2014/05/01 08:10:28  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>
