=== sstangl/tuja-vortaro/revo/src/dtd/vokoxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--****************************************************
          KADRA STRUKTURO DE VORTARO
********************************************************-->

<!-- [vortaro] Radiko de la strukturarbo de vortaro. La elemento ampleksas
la tutan vortaron.<p>
Ĝi entenas aŭ prologon, precipan parton kaj epilogon aŭ plurajn
artikolojn. Prologo kaj epilogo estas nedevigaj. La ebleco de rekta
enteno de artikolo ne estas destinita por kompletaj vortaroj, sed por
eltiroj aŭ unuopa artikolo.-->

<!ELEMENT vortaro ((prologo?,precipa-parto,epilogo?)|art+)>

<!-- [prologo] Prologo de la vortaro. Ĝi povas enteni la titolo(j)n 
kaj aŭtoro(j)n de la vortaro kaj aliajn tekstojn.-->

<!ELEMENT prologo (#PCDATA|titolo|autoro|alineo)*>

<!-- [epilogo] Epilogo de la vortaro. Ĝia strukturo momente ne estas
specifita. Ĝi povas enhavi iun tekston.-->

<!ELEMENT epilogo (#PCDATA|alineo)*>

<!-- [titolo] Titolo de la vortaro. Ĝi estas entenata en la 
prologo. Pluraj titoloj estas permesitaj.-->

<!ELEMENT titolo (#PCDATA)>

<!-- [autoro] Indiko de aŭtoro(j) de la vortaro. 
Ĝi estas enhavata en la prologo kaj povas okazi tie plurfoje.-->

<!ELEMENT autoro (#PCDATA)>

<!-- [alineo] unuopa alineo en la prologo-teksto -->

<!ELEMENT alineo (#PCDATA|url)*>

<!-- [precipa-parto] Precipa parto de la vortaro. Ĝi enhavas rekte ĉiujn
artikolojn aŭ sekciojn aŭ partojn. 
Diversaj partoj povas dividi diversajn lingvojn de la kapvortoj.
Sekcioj grupigas vortojn komencighantajn je sama litero.
-->

<!ELEMENT precipa-parto (parto+|sekcio+|art+)>

<!-- [parto] Vortaroparto. Ĝi estas entenata en la precipa parto. Parto normale
prezentas unu lingvon en plurlingva vortaro aŭ lingvodirekton en
dulingva vortaro. Ĝia atributo <dfn>lng</dfn> indikas la lingvon de
la kapvortoj en la parto.-->

<!ELEMENT parto (sekcio+|art+)>
<!ATTLIST parto
	lng CDATA #IMPLIED
>

<!-- [sekcio] Sekcio en vortaro. Ĝi estas entenata en la precipa parto aŭ en
parto de ĝi kaj normale entenas ĉiujn artikolojn, kies kapvorto
komenciĝas je sama litero. La atributo <dfn>lit</dfn> indikas tiun
komencliteron.-->

<!ELEMENT sekcio (art+)>
<!ATTLIST sekcio
	lit CDATA #IMPLIED
>

<!-- ******************************************************
             STRUKTURO DE ARTIKOLO
***********************************************************-->

<!-- [%priskribaj-elementoj] La unuo <dfn>priskribaj-elementoj</dfn> 
listigas ĉiujn strukturilojn, kiuj priskribas kapvorton aŭ unuopan 
sencon de ĝi. Ĉar ili povas okazi multloke en la strukturo de 
artikolo estas avantaĝe difini tiun ĉi unuon.-->

<!-- priskribaj elementoj -->
<!ENTITY % priskribaj-elementoj 
  "fnt|gra|uzo|dif|ekz|rim|ref|refgrp|trd|trdgrp|bld|adm|url|mlg|lstref|tezrad">

<!-- [%tekst-stiloj] La unuo <dfn>tekst-stiloj</dfn> 
listigas ĉiujn strukturilojn, kiuj donas stilon al tekstoparto,
ekz. emfazita, citilita, altigita aŭ malaltigita teksto.
Aliaj elementoj klarigo kaj tildo kaj sencreferenco same povas esti
multloke, do ankaŭ ili estas listigitaj tie ĉi. -->

<!-- tekst-stiloj -->
<!ENTITY % tekst-stiloj "tld|sncref|klr|em|sup|sub|ctl|frm">

<!-- [art] Unuopa artikolo de la vortaro. Ĝi povas okazi en
<dfn>vortaro</dfn> (se ne ekzistas precipa-parto),
<dfn>precipa-parto</dfn>, <dfn>parto</dfn> aŭ <dfn>sekcio</dfn>. Tio
dependas de la konkreta strukturo de la vortaro. Ĉiu artikolo
entenas unue kapvorton kaj poste aŭ priskribajn elementojn aŭ plurajn
derivaĵojn aŭ plurajn sencojn de la kapvorto aŭ subartikolojn. -->

<!ELEMENT art (kap,(subart|drv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST art
	mrk CDATA #REQUIRED
>

<!-- [subart] Subartikolo. Ĝi povas okazi en <dfn>artikolo</dfn>,
se la signifoj de vorto (ofte ĉe prepozicioj kaj afiksoj) estas
tre diversaj. -->

<!ELEMENT subart (drv|snc|%priskribaj-elementoj;)*>

<!-- [drv] Derivaĵo ene de artikolo. Unu artikolo povas priskribi plurajn
derivaĵojn de la kapvorto. Derivaĵo komenciĝas ja kapvorto kaj
priskribaj elementoj pri ĝi aŭ el unu aŭ pluraj sencoj aŭ el unu aŭ
pluraj subdividoj <dfn>subdrv</dfn>.-->

<!ELEMENT drv (kap,(subdrv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST drv
	mrk ID #REQUIRED
>

<!-- [var] variaĵo de la vorto, ekz. meĥaniko - mekaniko, pomarbo -
pomujo. Ĝi povas enhavi fontindikon k.s., sed ankaŭ rimarkojn 
kaj ekzemplojn, sed ĝi ne havas propran difinon. Ĝi aperas ene
de kapvorto, ĉar ĝi ja estas ĝia variaĵo.
-->

<!ELEMENT var (kap,(uzo|klr|ekz|rim)*)>

<!-- [subdrv] Subderivaĵo. Ĝi grupigas plurajn proksimajn sencojn, se la
priskribita vorto havas tre multajn sencojn. Tio povas
rezulti en pli klara strukturo de la artikolo. La subdividaĵoj
estas nombrataj per A), B), ... -->

<!ELEMENT subdrv (snc|%priskribaj-elementoj;)*>

<!-- [snc] Senco de unuopa vorto en artikolo. Komparu la latinajn ciferojn en
la artikoloj de PIV. Per mrk oni povas referenci sencon de alie. Per ref oni
referencas al alia senco samartikola (uzata en malmultaj longaj artikoloj, ekz.
"al". Per num la senco ricevas numeron. Atentu, ke future simbolaj nomoj por
la sencoj estos perferataj kaj do numerado okazas automate ignorante la atributon
num. -->

<!ELEMENT snc (subsnc|%priskribaj-elementoj;)*>
<!ATTLIST snc
	mrk ID #IMPLIED
        num CDATA #IMPLIED
	ref CDATA #IMPLIED
>

<!-- [subsnc] Subsenco ene de senco. Ĝi redonas subtilaĵojn ene de unu senco.
Ili estas nombrataj per a), b), ... -->

<!ELEMENT subsnc (%priskribaj-elementoj;)*>
<!ATTLIST subsnc
	mrk ID #IMPLIED
        ref CDATA #IMPLIED
>

<!-- [sncref] Referenco al alia senco. Tiu elemento estas anstatauigata
 per la numero de la referencita senco. Vi povas forlasi la atributon 
 ref, se ekzistas parenca elemento ref, kies atributo cel montras al la
 referencita senco.
-->

<!ELEMENT sncref EMPTY>
<!ATTLIST sncref
       ref CDATA #IMPLIED
>

<!-- ************************************************
            STRUKTUROJ DE DETALAJ ELEMENTOJ
*****************************************************-->

<!-- [kap] kapvorto okazas en du kuntekstoj - komence de artikolo
kaj komence de derivaĵo, en la unua kazo ĝi signas radikon
en la dua kazo ĝi konsistas el iuj literoj kaj eble tildo
refencanta al la kapvorto, krome en la kapvorto povas okazi
fontindiko.
-->

<!ELEMENT kap (#PCDATA|rad|ofc|fnt|tld|var)*>

<!-- [rad] Radiko de kapvorto. Ĝi estas bezonata por anstaŭigo
de tildoj. Sekve la "radiko" de afiksoj kaj finaĵoj estu
ili mem, sen la streketoj antaŭe aŭ malantaŭe.-->

<!ELEMENT rad (#PCDATA)>

<!-- [ofc] Oficialeco de la kapvorto/derivajho, 
  povas esti *, 1, ..., 8 kiel en PIV -->

<!ELEMENT ofc (#PCDATA)>

<!-- [fnt] Fonto enhavas informojn pri autoro, verko, trovloko
au aliajn informojn.-->

<!ELEMENT fnt (#PCDATA|bib|aut|vrk|lok|url)*>

<!-- [gra] kiel grammatikaj informoj momente estas permesataj
nur indiko de la vortspeco.-->

<!ELEMENT gra (#PCDATA|vspec)*>

<!-- [vspec] Vortspeco. Ekz. subst. por substantivo; tr./ntr.
por transitivaj kaj netransitivaj verboj ktp.-->

<!ELEMENT vspec (#PCDATA)>

<!-- [uzo] La uzo povas esti stilo, fako, regiono aŭ alia klarigo,
kiel estas uzata la vorto au termino. Por la fakoj kaj stiloj uzu
unu el la aliloke listigitaj mallongigoj.
-->

<!ELEMENT uzo (#PCDATA|tld)*>
<!ATTLIST uzo
	tip (fak|reg|klr|stl) #IMPLIED
>

<!-- [dif] Difino estas la frazo difinanta la vorton, sencon aŭ
subsencon. Ĝi povas esti ankaŭ en alia(j) lingvo(j) ol la vorto
mem. La lingvon indikas la atributo <dfn>lng</dfn>.
-->

<!ELEMENT dif (#PCDATA|trd|trdgrp|ref|refgrp|ekz|snc|%tekst-stiloj;)*>
<!ATTLIST dif
	lng CDATA #IMPLIED
>

<!-- [ekz] Ekzemplo konsistas el ekzemplofrazo,
klarigoj kaj fonto.
-->

<!ELEMENT ekz (#PCDATA|fnt|uzo|ref|refgrp|ind|trd|trdgrp|%tekst-stiloj;)*>
<!ATTLIST ekz
	mrk ID #IMPLIED
>

<!-- [rim] Rimarko povas enhavi iujn indikojn pri la vorto aŭ
senco, krome referencojn, ekzemplojn, emfazitajn partojn.
-->
<!ELEMENT rim (#PCDATA|ref|refgrp|ekz|aut|fnt|%tekst-stiloj;)*>
<!ATTLIST rim
        num CDATA #IMPLIED
	mrk ID #IMPLIED
> 

<!-- [refgrp] Referencgrupo grupigas plurajn samtipajn
referencojn. La tipon indikas la atributo <dfn>tip</dfn>.
Tiukaze ne uzu la atributon <dfn>tip</dfn> en la subelementoj
<dfn>ref</dfn>!
-->

<!ELEMENT refgrp (#PCDATA|ref)*>
<!ATTLIST refgrp
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) "vid"
>

<!-- [ref] Referenco montras al alia, simil- aŭ alisignifa vorto,
oni povas distingi diversajn rilattipon al la
referencita vorto. La enhavo de la referenco estas tio, kio
aperas en la legebla teksto. La referencitan vorton mem
oni difinas per la atributo "cel". La celon oni plej
bone difinas per: radiko.derivaĵo.difino, oni povas uzi
la numeron de la difino au derivaĵo. Plej bone oni
generas la markojn (t.e. la eblaj celoj de referenco)
aŭtomate por minimumigi erarojn.
La atributoj "lst" kaj "val" servas por referenci al vortlisto (tip="lst"),
ekz. monatoj. Se temas pri ordigita listo, vi povas indiki valoron per "val",
ekz. "3" che la monato marto.
-->

<!ELEMENT ref (#PCDATA|tld|klr|sncref)*>
<!ATTLIST ref
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) #IMPLIED
	cel CDATA #REQUIRED
        lst CDATA #IMPLIED
	val CDATA #IMPLIED
>

<!-- [tez] NE PLU UZU! Tezaŭra nodo. Ĝi permesas referenci al tio, same kiel
 al kap kaj mem povas referenci al alia nodo.
-->
<!ELEMENT tez (#PCDATA|tld|klr|ref|refgrp)*>
<!ATTLIST tez
        mrk CDATA #REQUIRED
        tip (super|malprt|listo) #IMPLIED
	cel CDATA #REQUIRED
>

<!-- [lstref] Referenco al vortlisto el artikolo.
-->
<!ELEMENT lstref (#PCDATA|tld|klr)*>
<!ATTLIST lstref
        lst CDATA #REQUIRED
>

<!-- [tezrad] Tezaŭraradiko. La kapvorto aperas en la enir-listo
de la tezaŭro. Se vi uzas la atributon fak, ĝi aperas en la 
struktura enirlisto de la fako -->
<!ELEMENT tezrad EMPTY>
<!ATTLIST tezrad
        fak CDATA #IMPLIED
>

<!-- [trdgrp] Tradukgrupo kunigas diversajn tradukojn de
sama lingvo.
-->
<!ELEMENT trdgrp (#PCDATA|trd)*>
<!ATTLIST trdgrp
	lng CDATA #REQUIRED
>

<!-- [trd] Traduko kosistas el traduka vorto aŭ frazo
kaj klarigoj, poste povos sekvi aliaj elementoj.
-->
<!ELEMENT trd (#PCDATA|klr|ind|mll|ofc)*>
<!ATTLIST trd
	lng CDATA #IMPLIED
>

<!-- [ind] Parto de traduko, kiu liveras la kapvorton en la
indekso, do &lt;trd&gt;sich &lt;ind&gt;bem&uuml;hen&lt;/ind&gt;&lt;/trd&gt;
aperas sub bem&uuml;hen. Aŭ parto de ekzemplo aŭ bildpriskribo, al
kiu rilatas internaj tradukoj ktp.
-->
<!ELEMENT ind (#PCDATA|tld|klr|mll)*>

<!ELEMENT mll (#PCDATA|tld|klr|ind)*>
<!ATTLIST mll
        tip (kom|mez|fin) #IMPLIED
>

<!-- [bld] Bildo povas ilustri iun vorton aŭ sencon. Per la
atributo <dfn>lok</dfn> ĝi
referencas al ekstera dosiero, kiu entenas la bildon.
Per <dfn>alt</dfn> kaj <dfn>lrg</dfn> vi povas doni fiksan formaton.
Per <dfn>tip</dfn> vi donas tipon de la bildo, t.e. <dfn>img</dfn>
por JPEG, GIF, PNG-bildo, <dfn>svg</dfn> por SVG-vektorgrafiko.
-->
<!ELEMENT bld (#PCDATA|tld|klr|fnt|ind|trd|trdgrp)*>
<!ATTLIST bld
	lok CDATA #REQUIRED
	mrk ID #IMPLIED
	tip (img|svg) "img"
	alt CDATA #IMPLIED 
	lrg CDATA #IMPLIED
>

<!-- [adm] Administraj informoj estu por redaktado. Ili povus
enhavi informojn pri kreodato, ŝanĝdato, aŭtoro, eraroj kaj
plibonigproponoj pri artikolo. Ĝia strukturo ankoraŭ estas
diskutatebla.
-->
<!ELEMENT adm (#PCDATA|aut)*>

<!-- [tld] Tildo rilatas al la radiko, donita en la kapvorto
ĝi ne bezonas enhavon. La atributo <dfn>lit</dfn> indikas alian
komencliteron ol havas la radiko. Grava por majuskligo kaj
minuskligo.
-->
<!ELEMENT tld EMPTY>
<!ATTLIST tld
            lit CDATA #IMPLIED>       

<!-- [klr] Klarigo pri vorto, difino, ekzemplo ktp.-->
<!ELEMENT klr (#PCDATA|trd|trdgrp|ekz|ref|refgrp|%tekst-stiloj;)*>
<!ATTLIST klr
            tip (ind|amb) #IMPLIED>

<!-- [bib] Bibliografia indiko por fonto, estas mallongigo el
listo de difinitaj bibliografieroj kaj anstataŭas verko- kaj aŭtoroindikon
en la fontoj.
-->
<!ELEMENT bib (#PCDATA)*>

<!-- [vrk] Verko, en kiu troviĝas citita frazo aŭ vorto -->
<!ELEMENT vrk (#PCDATA|url)*>

<!-- [lok] Loko, kie troviĝas citita frazo aŭ vorto en verko -->
<!ELEMENT lok (#PCDATA|url)*>

<!-- [aut] Aŭtoro de citita frazo aŭ verko -->
<!ELEMENT aut (#PCDATA)>

<!-- [frm] Matematika au kemia formulo -->
<!ELEMENT frm (#PCDATA|sup|sub|g|k)*>

<!-- [g] Grasa parto de formulo, ekz. vektoro, matrico k.s.,
  bv. uzi nur en frm -->
<!ELEMENT g (#PCDATA)*>

<!-- [k] Kursiva parto de formulo, ekz. variablo k.s.,
  bv. uzi nur en frm -->
<!ELEMENT k (#PCDATA)*>

<!-- [em] Emfazo. Normale grase skribata vortoj.-->
<!ELEMENT em (#PCDATA|tld)*>

<!-- [sup] altigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sup (#PCDATA|g|k)*>

<!-- [sub] malaltigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sub (#PCDATA|g|k)*>

<!-- [ctl] citilita teksto, ekz. memindika uzo de vorto -->
<!ELEMENT ctl (#PCDATA|tld|em|frm)*>

<!-- [url] Referenco al iu ekstera dosiero. En la HTML-versio de vortaro
tio fariĝas &lt;a href=...&gt; Anstataŭ la TTT-ejo prefere uzu
la alinomojn difinitajn en la DTD, ĉar alikaze la referencoj tro
ofte malvalidiĝus. -->

<!ELEMENT url (#PCDATA)>
<!ATTLIST url 
          ref CDATA #IMPLIED>

<!-- [mlg] mallongigo de la kapvorto, ekz. che nomoj de organizajhoj. 
Per "kod" vi povas indiki devenon de la mallongigo, ekz. ISO-3166 ĉe landokodoj -->

<!ELEMENT mlg (#PCDATA)>
<!ATTLIST mlg
          kod CDATA #IMPLIED>




<!-- *************************************************
                   LITEROJ
******************************************************
-->

<!ENTITY % signoj SYSTEM "../dtd/vokosgn.dtd">
%signoj;

<!-- ************************************************
                   MALLONGIGOJ
*****************************************************
-->

<!ENTITY % mallongigoj SYSTEM "../dtd/vokomll.dtd">
%mallongigoj;

<!-- *************************************************
                   URLoj
******************************************************
-->

<!ENTITY % urloj SYSTEM "../dtd/vokourl.dtd">
%urloj;

=== sstangl/tuja-vortaro/revo/src/xml/mizoram.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: mizoram.xml,v 1.1 2014/09/17 01:11:02 revo Exp $">
<kap>
  <rad>Mizoram</rad>/o <fnt><bib>LanLin</bib></fnt>
</kap>
<drv mrk="mizoram.0o">
  <kap><tld/>o</kap>
  <snc mrk="mizoram.0o.GEOG">
    <uzo tip="fak">GEOG</uzo>
    <dif>
      Gubernio en la orienta parto de
      <ref tip="malprt" cel="hind.H0ujo.POL">Hindujo</ref>:
      <ekz>
        en <klr>...</klr> <tld/>o en Barato, 
        &ccirc;akma-parolantaj infanoj havas instruistojn kiuj apartenas al 
        la plimulta etnogrupo Mizoj
        <fnt>
          <aut>A. Giridhar Rao</aut>,
          <vrk><url ref="http://www.ipernity.com/blog/giridhar/159540">
          Lingva diskriminacio en Mizoramo</url></vrk>,
          <lok>2009-06-15</lok>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="fr">Mizoram</trd>
</drv>
</art>

<!--
$Log: mizoram.xml,v $
Revision 1.1  2014/09/17 01:11:02  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/garden.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: garden.xml,v 1.23 2015/09/21 11:10:15 revo Exp $">
<kap>
  <ofc>1</ofc>
  <rad>gardeni</rad>/o <fnt><bib>PV</bib></fnt>
</kap>
<drv mrk="garden.0o">
  <kap><tld/>o</kap>
  <snc mrk="garden.0o.BOT">
    <uzo tip="fak">BOT</uzo>
    <dif>
      &Ccirc;iamverda arbeto el malsekaj tropikaj regionoj kun belaj 
      dikpetalaj floroj kaj brilaj malhelverdaj folioj,
      <ref tip="lst" cel="genr.0o.BIO"
      lst="voko:botanikaj_genroj">genro</ref> el familio <ref
      tip="malprt"
      cel="rubi.0oj.BOT">rubiacoj</ref>
      (<trd lng="la">Gardenia</trd>):
      <ekz>
        la italo alvenis nokti&gcirc;e kun <tld/>o en la butontruo de la 
        jakfaldo
        <fnt><aut>G. Garc&iacute;a M&aacute;rquez, trad. F. de Diego</aut>, <vrk>Cent 
        Jaroj da Soleco</vrk>, <lok>Fonto, 1992</lok></fnt>;
      </ekz>
      <ekz>
        li! Alfredo, en blanka kompleto, kun ru&gcirc;a kravato kaj du 
        <tld/>oj enmane!
        <fnt>
          <aut>M. Fern&aacute;ndez</aut>,
          <vrk>Du Gardenioj</vrk>,
          <lok>Ekstremoj, 1997</lok>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="en">gardenia</trd>
  <trd lng="be">&c_g;&c_a;&c_r;&c_d;&c_e;&c_n;&c_ib;&c_ja;</trd>
  <trd lng="ca">gard&egrave;nia</trd>
  <trd lng="cs">gard&eacute;nie</trd>
  <trd lng="de">Gardenie</trd>
  <trd lng="el">&gamma;&alfa;&rho;&delta;&epsilon_ton;&ny;&jota;&alfa;</trd>
  <trd lng="es">gardenia</trd>
  <trd lng="fr">gard&eacute;nia</trd>
  <trd lng="hu">gard&eacute;nia</trd>
  <trd lng="it">gardenia</trd>
  <trd lng="nl">gardeniastruik</trd>
  <trd lng="pl">gardenia</trd>
  <trd lng="pt">gard&ecirc;nia</trd>
  <trd lng="ru">&c_g;&c_a;&c_r;&c_d;&c_je;&c_n;&c_i;&c_ja;</trd>
  <trd lng="sk">gard&eacute;nia</trd>
</drv>
</art>
<!--
$Log: garden.xml,v $
Revision 1.23  2015/09/21 11:10:15  revo
Sebastian Cyprych: +trd pl

Revision 1.22  2015/09/14 14:10:18  revo
Cindy Moon McKee: +trd en

Revision 1.21  2015/07/04 08:37:34  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.20  2015/06/29 16:29:39  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.19  2013/08/29 09:10:20  revo
Wolfram Diestel: referenco al listo bot genroj

Revision 1.18  2012/08/04 19:10:16  revo
Marc Rausell: + trd ca

Revision 1.17  2010/08/09 16:30:19  revo
Jeromo Vasxe: kor. 1 ekz

Revision 1.16  2007/05/03 16:51:45  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/preben.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: preben.xml,v 1.14 2015/07/04 08:37:41 revo Exp $">
<kap>
  <rad>prebend</rad>/o
  <fnt>Z</fnt>
</kap>
<drv mrk="preben.0o">
  <kap><tld/>o</kap>
  <uzo tip="fak">KAT</uzo>
  <snc>
    <dif>
      Rento alligita al eklezia titolo.
    </dif>
  </snc>
  <trd lng="be">&c_p;&c_r;&c_e;&c_b;&c_e;&c_n;&c_d;&c_a;</trd>
  <trdgrp lng="cs">
    <trd>obročí</trd>,
    <trd>prebenda</trd>
  </trdgrp>
  <trd lng="de">Pr&auml;bende</trd>
  <trd lng="en">prebend</trd>
  <trdgrp lng="hu">
    <trd>praebenda</trd>,
    <trd>egyh&aacute;zi <ind>javadalom</ind></trd>
  </trdgrp>
  <trd lng="it">prebenda</trd>
  <trdgrp lng="nl">
    <trd>prebende</trd>,
    <trd>kerkelijk <ind>rente</ind></trd>
  </trdgrp>
  <trd lng="pl">prebenda</trd>
  <trd lng="pt">prebenda</trd>
  <trd lng="ru">&c_p;&c_r;&c_je;&c_b;&c_je;&c_n;&c_d;&c_a;</trd>
  <trdgrp lng="sk">
    <trd>benefícium</trd>,
    <trd>obročie</trd>,
    <trd>prebenda</trd>
  </trdgrp>
</drv>
</art>
<!--
$Log: preben.xml,v $
Revision 1.14  2015/07/04 08:37:41  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.13  2015/06/29 16:40:18  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.12  2010/11/04 17:31:09  revo
Antonio Codazzi: +trd it

Revision 1.11  2009/06/09 16:31:40  revo
Russ Williams: +trd en

Revision 1.10  2008/05/20 16:30:41  revo
Sebastian Cyprych: +trd pl

Revision 1.9  2006/03/17 17:32:20  revo
Tulio Flores: +tr pt

Revision 1.8  2005/01/15 17:32:28  revo
Dmitri Gabinski: +trd be

Revision 1.7  2002/08/05 17:31:42  revo
Jozefo Horvath: +trd hu

Revision 1.6  2001/12/24 19:29:23  revo
Yury Finkel: +trd ru

Revision 1.5 2001/07/01 18:12:22 revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/sabek.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: sabek.xml,v 1.17 2015/11/26 15:10:21 revo Exp $">
<kap>
  <rad>sabek</rad>/o <fnt><bib>PV</bib></fnt>
</kap>
<drv mrk="sabek.0o">
  <kap><tld/>o</kap>
  <snc mrk="sabek.0o.MUZ">
    <uzo tip="fak">MUZ</uzo>
    <dif>
      Antikva hebrea
      <ref tip="lst" cel="instru2.kord0o.MUZ"
      lst="voko:kordinstrumentoj">kordinstrumento</ref>
      triangula:
      <ekz>
        &ccirc;iuj popoloj eka&ubreve;dis la sonon de korno, fluto, harpo, <tld/>o,
        psaltero, kaj diversaj muzikaj instrumentoj
        <fnt><bib>MT</bib>, <lok>&Dan; 3:7</lok></fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="cs">sabek</trd>
  <trd lng="de">Sambuka</trd>
  <trd lng="en">sabeca</trd>
  <trd lng="fr">sambuque</trd>
  <trd lng="hu">sambuca <klr>(h&aacute;romsz&ouml;g alak&uacute; h&aacute;rfa)</klr></trd>
  <trd lng="it">sambuca</trd>
  <trd lng="nl">sabbeca</trd>
  <trdgrp lng="pt">
   <trd>sabeca</trd>
  </trdgrp>
  <trdgrp lng="ru">
    <trd>&c_s;&c_a;&c_m;&c_b;&c_u;&c_k;</trd>,
    <trd>&c_s;&c_a;&c_m;&c_b;&c_u;&c_k;&c_a;</trd>
  </trdgrp>
  <trd lng="sk">sabek</trd>
</drv>
</art>
<!--
$Log: sabek.xml,v $
Revision 1.17  2015/11/26 15:10:21  revo
Cindy Moon McKee: +trd en

Revision 1.16  2015/07/04 08:37:43  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.15  2015/06/29 16:33:22  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.14  2013/09/08 18:11:36  revo
Wolfram Diestel: ref al listo kordinstrumentoj

Revision 1.13  2011/01/06 15:25:15  revo
Jeromo Vasxe: kor. 1 fusxitan fnt

Revision 1.12  2009/09/19 16:30:55  revo
Antonio Codazzi: +trd it

Revision 1.11  2006/02/06 17:31:26  revo
Tulio Flores: +trd pt

Revision 1.10  2005/08/17 16:31:31  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/afoni.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: afoni.xml,v 1.18 2015/07/04 08:37:29 revo Exp $">
<kap>
  <rad>afoni</rad>/o
</kap>
<drv mrk="afoni.0o">
  <kap><tld/>o</kap>
  <uzo tip="fak">MED</uzo>
  <snc>
    <dif>
      Senvo&ccirc;eco.
    </dif>
  </snc>
  <trdgrp lng="be">
    <trd>&c_a;&c_f;&c_o;&c_n;&c_ib;&c_ja;</trd>,
    <trd>&c_s;&c_t;&c_r;&c_a;&c_t;&c_a; &c_g;&c_o;&c_l;&c_a;&c_s;&c_u;</trd>
  </trdgrp>
  <trd lng="ca">afonia</trd>
  <trdgrp lng="cs">
    <trd>afonie</trd>,
    <trd>bezhlasnost</trd>
  </trdgrp>
  <trdgrp lng="de">
     <trd>Verlust der Stimme</trd>,
     <trd>Stimmverlust</trd>,
     <trd>Stimmlosigkeit</trd>
  </trdgrp>
  <trd lng="en">aphonia</trd>
  <trd lng="es">afon&iacute;a</trd>
  <trd lng="fr">aphonie</trd>
  <trdgrp lng="hu">
     <trd>af&oacute;nia</trd>,
     <trd>hangveszt&eacute;s</trd>,
     <trd>hangtalans&aacute;g</trd>
  </trdgrp>
  <trd lng="it">afonia</trd>
  <trd lng="nl">sprakeloosheid</trd>
  <trd lng="pt">afonia</trd>
  <trdgrp lng="ru">
    <trd>&c_a;&c_f;&c_o;&c_n;&c_i;&c_ja;</trd>,
    <trd>&c_p;&c_o;&c_t;&c_je;&c_r;&c_ja; &c_g;&c_o;&c_l;&c_o;&c_s;&c_a;</trd>
  </trdgrp>
  <trdgrp lng="sk">
    <trd>af&oacute;nia</trd>,
    <trd>bezhlasnos≈•</trd>
  </trdgrp>
</drv>
</art>
<!--
$Log: afoni.xml,v $
Revision 1.18  2015/07/04 08:37:29  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.17  2015/06/28 12:03:35  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.16  2012/07/31 09:10:32  revo
Marc Rausell: + trd ca

Revision 1.15  2011/11/02 11:10:23  revo
Antonio Codazzi: +trd it

Revision 1.14  2005/04/27 16:33:16  revo
Raul Salinas Monteagudo: korekto trd es

Revision 1.13  2003/10/28 17:31:47  revo
Dmitri Gabinski: +trd be

Revision 1.12  2003/05/17 16:31:48  revo
Viliam Bur: +trd sk

Revision 1.11  2002/10/30 18:37:23  revo
Jozefo Horvath: +trd hu

Revision 1.10  2002/05/06 16:33:31  revo
Ulrich Fellmann: + 3 trd de

Revision 1.9  2002/04/22 16:33:12  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/vincxestr.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: vincxestr.xml,v 1.3 2012/08/13 10:10:21 revo Exp $">
<kap>
  <rad>vin&ccirc;estr</rad>/o
</kap>
<drv mrk="vincxestr.0o">
  <kap><tld/>o</kap>
  <snc mrk="vincxestr.0o.ARM">
    <dif>
      Pafilo el la samnoma kompanio, precipe <ref tip="super" 
      cel="karabe.0o.ARM">karabeno</ref> produktita fine de la 19a 
      jarcento kaj ofte figurata en vakerfilmoj:
      <ekz>
        lia nevo estas kolektanto de modelaj fusiloj, kaj li ser&ccirc;as 
        iun modelon de <tld lit="V"/>o
        <fnt>
          <aut>Aoyama T.</aut>,
          <vrk><url
          ref="http://homepage1.nifty.com/aoyama-t/fusilo.htm">
          La Ser&ccirc;ado de Vincxestro</url></vrk>,
          <lok>2002-05-27</lok>
        </fnt>;
      </ekz>
      <ekz>
        kun korka kasko sur la kapo kaj <tld/>o en la mano li tretas 
        per la piedo rinoceron
        <fnt>
          <aut>S. Lem, trad. K. Du&scirc;enko, trad. J. Finkel</aut>,
          <vrk><url ref="http://www.esperanto.mv.ru/Lem/index.html">
          Surloka esploro</url></vrk>,
          <lok>2003</lok>
        </fnt>.
      </ekz>
    </dif>
  </snc>
  <trd lng="ca"><klr>[fusell]</klr> Winchester</trd>
  <trd lng="fr">winchester</trd>
  <trd lng="hu">winchester</trd>
</drv>
</art>

<!--
$Log: vincxestr.xml,v $
Revision 1.3  2012/08/13 10:10:21  revo
Marc Rausell: + trd ca

Revision 1.2  2008/07/16 16:31:05  revo
Jozefo Horvath: +trd hu

Revision 1.1  2007/05/19 17:02:55  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/alial.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: alial.xml,v 1.5 2015/07/04 08:37:30 revo Exp $">
<kap>
    <rad>alial</rad>
</kap>
<drv mrk="alial.0">
  <kap><tld/></kap>
  <snc>
    <uzo tip="fak">GRA</uzo>
    <uzo tip="stl">EVI</uzo>
    <dif>
    =<ref tip="dif" cel="ali.0a.diferenca">ali</ref>ka&ubreve;ze.
    </dif>
    <rim>
    Tiu neoficiala malofta vorto ne apartenas al la <ref tip="dif"
    cel="tabel.0vorto">tabelvortoj</ref> kaj ties uzo kunportus
    drastajn &scirc;an&gcirc;ojn en la lingvon.
    </rim>
  </snc>
  <trd lng="cs">z jiného důvodu</trd>
  <trd lng="sk">z iného dôvodu</trd>
</drv>
</art>

<!--
$Log: alial.xml,v $
Revision 1.5  2015/07/04 08:37:30  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.4  2015/06/28 12:03:35  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.3  2014/02/06 16:10:13  revo
Damien Brucker: +ref

Revision 1.2  2014/02/06 14:10:13  revo
Damien Brucker: +rim

Revision 1.1  2014/02/06 13:10:15  revo
Damien Brucker: nova artikolo

-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/gnetac.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: gnetac.xml,v 1.12 2013/08/25 16:11:32 revo Exp $">
<kap>
  <rad>gnetac</rad>/oj
</kap>

<drv mrk="gnetac.0oj">
  <kap>
    <tld/>oj
  </kap>
  <uzo tip="fak">BOT</uzo>
  <snc>
    <dif>
      <ref tip="lst" cel="famili.0o.BIO"
      lst="voko:botanikaj_familioj">Familio</ref> de <ref tip="malprt"
      cel="gnet.0oplantoj">gnetoplantoj</ref>
      (<trd lng="la">Gnetaceae</trd>).
    </dif>
  </snc>
  <trd lng="ca">gnet&agrave;cies</trd>
  <trd lng="de">Gnetaceae</trd>
  <trd lng="fr">gn&eacute;tac&eacute;es</trd>
  <trd lng="hu">gn&eacute;tumf&eacute;l&eacute;k</trd>
  <trd lng="nl">gnetacee&euml;n</trd>
  <trd lng="pt">gnet&aacute;ceas</trd>
  <trdgrp lng="ru">
    <trd>&c_g;&c_n;&c_je;&c_t;&c_o;&c_v;&c_y;&c_je;<klr tip="ind"> (&c_s;&c_je;&c_m;&c_je;&c_j;&c_s;&c_t;&c_v;&c_o;)</klr></trd>,
    <trd>&c_h;&c_v;&c_o;&c_j;&c_n;&c_i;&c_k;&c_o;&c_v;&c_y;&c_je; <klr tip="amb">(&c_s;&c_je;&c_m;&c_je;&c_j;&c_s;&c_t;&c_v;&c_o;)</klr></trd>
  </trdgrp>
</drv>
</art>
<!--
$Log: gnetac.xml,v $
Revision 1.12  2013/08/25 16:11:32  revo
Wolfram Diestel: referenco al listo bot familioj

Revision 1.11  2011/12/05 14:10:16  revo
Marc Rausell: kataluna traduko

Revision 1.10  2007/07/03 16:30:23  revo
Wieland Pusch: +trd de

Revision 1.9  2007/04/29 16:31:50  revo
Tulio Flores: +tr pt

Revision 1.8  2003/11/18 17:31:02  revo
Jozefo Horvath: +trd hu

Revision 1.7  2002/03/13 17:35:55  revo
Yury Finkel: kor trd ru

Revision 1.6  2002/01/11 17:33:16  revo
Paul Peeraerts: kor de tajperaro

Revision 1.5  2002/01/10 17:31:43  revo
-->
</vortaro>
