=== sstangl/tuja-vortaro/revo/src/dtd/vokoxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--****************************************************
          KADRA STRUKTURO DE VORTARO
********************************************************-->

<!-- [vortaro] Radiko de la strukturarbo de vortaro. La elemento ampleksas
la tutan vortaron.<p>
Ĝi entenas aŭ prologon, precipan parton kaj epilogon aŭ plurajn
artikolojn. Prologo kaj epilogo estas nedevigaj. La ebleco de rekta
enteno de artikolo ne estas destinita por kompletaj vortaroj, sed por
eltiroj aŭ unuopa artikolo.-->

<!ELEMENT vortaro ((prologo?,precipa-parto,epilogo?)|art+)>

<!-- [prologo] Prologo de la vortaro. Ĝi povas enteni la titolo(j)n 
kaj aŭtoro(j)n de la vortaro kaj aliajn tekstojn.-->

<!ELEMENT prologo (#PCDATA|titolo|autoro|alineo)*>

<!-- [epilogo] Epilogo de la vortaro. Ĝia strukturo momente ne estas
specifita. Ĝi povas enhavi iun tekston.-->

<!ELEMENT epilogo (#PCDATA|alineo)*>

<!-- [titolo] Titolo de la vortaro. Ĝi estas entenata en la 
prologo. Pluraj titoloj estas permesitaj.-->

<!ELEMENT titolo (#PCDATA)>

<!-- [autoro] Indiko de aŭtoro(j) de la vortaro. 
Ĝi estas enhavata en la prologo kaj povas okazi tie plurfoje.-->

<!ELEMENT autoro (#PCDATA)>

<!-- [alineo] unuopa alineo en la prologo-teksto -->

<!ELEMENT alineo (#PCDATA|url)*>

<!-- [precipa-parto] Precipa parto de la vortaro. Ĝi enhavas rekte ĉiujn
artikolojn aŭ sekciojn aŭ partojn. 
Diversaj partoj povas dividi diversajn lingvojn de la kapvortoj.
Sekcioj grupigas vortojn komencighantajn je sama litero.
-->

<!ELEMENT precipa-parto (parto+|sekcio+|art+)>

<!-- [parto] Vortaroparto. Ĝi estas entenata en la precipa parto. Parto normale
prezentas unu lingvon en plurlingva vortaro aŭ lingvodirekton en
dulingva vortaro. Ĝia atributo <dfn>lng</dfn> indikas la lingvon de
la kapvortoj en la parto.-->

<!ELEMENT parto (sekcio+|art+)>
<!ATTLIST parto
	lng CDATA #IMPLIED
>

<!-- [sekcio] Sekcio en vortaro. Ĝi estas entenata en la precipa parto aŭ en
parto de ĝi kaj normale entenas ĉiujn artikolojn, kies kapvorto
komenciĝas je sama litero. La atributo <dfn>lit</dfn> indikas tiun
komencliteron.-->

<!ELEMENT sekcio (art+)>
<!ATTLIST sekcio
	lit CDATA #IMPLIED
>

<!-- ******************************************************
             STRUKTURO DE ARTIKOLO
***********************************************************-->

<!-- [%priskribaj-elementoj] La unuo <dfn>priskribaj-elementoj</dfn> 
listigas ĉiujn strukturilojn, kiuj priskribas kapvorton aŭ unuopan 
sencon de ĝi. Ĉar ili povas okazi multloke en la strukturo de 
artikolo estas avantaĝe difini tiun ĉi unuon.-->

<!-- priskribaj elementoj -->
<!ENTITY % priskribaj-elementoj 
  "fnt|gra|uzo|dif|ekz|rim|ref|refgrp|trd|trdgrp|bld|adm|url|mlg|lstref|tezrad">

<!-- [%tekst-stiloj] La unuo <dfn>tekst-stiloj</dfn> 
listigas ĉiujn strukturilojn, kiuj donas stilon al tekstoparto,
ekz. emfazita, citilita, altigita aŭ malaltigita teksto.
Aliaj elementoj klarigo kaj tildo kaj sencreferenco same povas esti
multloke, do ankaŭ ili estas listigitaj tie ĉi. -->

<!-- tekst-stiloj -->
<!ENTITY % tekst-stiloj "tld|sncref|klr|em|sup|sub|ctl|frm">

<!-- [art] Unuopa artikolo de la vortaro. Ĝi povas okazi en
<dfn>vortaro</dfn> (se ne ekzistas precipa-parto),
<dfn>precipa-parto</dfn>, <dfn>parto</dfn> aŭ <dfn>sekcio</dfn>. Tio
dependas de la konkreta strukturo de la vortaro. Ĉiu artikolo
entenas unue kapvorton kaj poste aŭ priskribajn elementojn aŭ plurajn
derivaĵojn aŭ plurajn sencojn de la kapvorto aŭ subartikolojn. -->

<!ELEMENT art (kap,(subart|drv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST art
	mrk CDATA #REQUIRED
>

<!-- [subart] Subartikolo. Ĝi povas okazi en <dfn>artikolo</dfn>,
se la signifoj de vorto (ofte ĉe prepozicioj kaj afiksoj) estas
tre diversaj. -->

<!ELEMENT subart (drv|snc|%priskribaj-elementoj;)*>

<!-- [drv] Derivaĵo ene de artikolo. Unu artikolo povas priskribi plurajn
derivaĵojn de la kapvorto. Derivaĵo komenciĝas ja kapvorto kaj
priskribaj elementoj pri ĝi aŭ el unu aŭ pluraj sencoj aŭ el unu aŭ
pluraj subdividoj <dfn>subdrv</dfn>.-->

<!ELEMENT drv (kap,(subdrv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST drv
	mrk ID #REQUIRED
>

<!-- [var] variaĵo de la vorto, ekz. meĥaniko - mekaniko, pomarbo -
pomujo. Ĝi povas enhavi fontindikon k.s., sed ankaŭ rimarkojn 
kaj ekzemplojn, sed ĝi ne havas propran difinon. Ĝi aperas ene
de kapvorto, ĉar ĝi ja estas ĝia variaĵo.
-->

<!ELEMENT var (kap,(uzo|klr|ekz|rim)*)>

<!-- [subdrv] Subderivaĵo. Ĝi grupigas plurajn proksimajn sencojn, se la
priskribita vorto havas tre multajn sencojn. Tio povas
rezulti en pli klara strukturo de la artikolo. La subdividaĵoj
estas nombrataj per A), B), ... -->

<!ELEMENT subdrv (snc|%priskribaj-elementoj;)*>

<!-- [snc] Senco de unuopa vorto en artikolo. Komparu la latinajn ciferojn en
la artikoloj de PIV. Per mrk oni povas referenci sencon de alie. Per ref oni
referencas al alia senco samartikola (uzata en malmultaj longaj artikoloj, ekz.
"al". Per num la senco ricevas numeron. Atentu, ke future simbolaj nomoj por
la sencoj estos perferataj kaj do numerado okazas automate ignorante la atributon
num. -->

<!ELEMENT snc (subsnc|%priskribaj-elementoj;)*>
<!ATTLIST snc
	mrk ID #IMPLIED
        num CDATA #IMPLIED
	ref CDATA #IMPLIED
>

<!-- [subsnc] Subsenco ene de senco. Ĝi redonas subtilaĵojn ene de unu senco.
Ili estas nombrataj per a), b), ... -->

<!ELEMENT subsnc (%priskribaj-elementoj;)*>
<!ATTLIST subsnc
	mrk ID #IMPLIED
        ref CDATA #IMPLIED
>

<!-- [sncref] Referenco al alia senco. Tiu elemento estas anstatauigata
 per la numero de la referencita senco. Vi povas forlasi la atributon 
 ref, se ekzistas parenca elemento ref, kies atributo cel montras al la
 referencita senco.
-->

<!ELEMENT sncref EMPTY>
<!ATTLIST sncref
       ref CDATA #IMPLIED
>

<!-- ************************************************
            STRUKTUROJ DE DETALAJ ELEMENTOJ
*****************************************************-->

<!-- [kap] kapvorto okazas en du kuntekstoj - komence de artikolo
kaj komence de derivaĵo, en la unua kazo ĝi signas radikon
en la dua kazo ĝi konsistas el iuj literoj kaj eble tildo
refencanta al la kapvorto, krome en la kapvorto povas okazi
fontindiko.
-->

<!ELEMENT kap (#PCDATA|rad|ofc|fnt|tld|var)*>

<!-- [rad] Radiko de kapvorto. Ĝi estas bezonata por anstaŭigo
de tildoj. Sekve la "radiko" de afiksoj kaj finaĵoj estu
ili mem, sen la streketoj antaŭe aŭ malantaŭe.-->

<!ELEMENT rad (#PCDATA)>

<!-- [ofc] Oficialeco de la kapvorto/derivajho, 
  povas esti *, 1, ..., 8 kiel en PIV -->

<!ELEMENT ofc (#PCDATA)>

<!-- [fnt] Fonto enhavas informojn pri autoro, verko, trovloko
au aliajn informojn.-->

<!ELEMENT fnt (#PCDATA|bib|aut|vrk|lok|url)*>

<!-- [gra] kiel grammatikaj informoj momente estas permesataj
nur indiko de la vortspeco.-->

<!ELEMENT gra (#PCDATA|vspec)*>

<!-- [vspec] Vortspeco. Ekz. subst. por substantivo; tr./ntr.
por transitivaj kaj netransitivaj verboj ktp.-->

<!ELEMENT vspec (#PCDATA)>

<!-- [uzo] La uzo povas esti stilo, fako, regiono aŭ alia klarigo,
kiel estas uzata la vorto au termino. Por la fakoj kaj stiloj uzu
unu el la aliloke listigitaj mallongigoj.
-->

<!ELEMENT uzo (#PCDATA|tld)*>
<!ATTLIST uzo
	tip (fak|reg|klr|stl) #IMPLIED
>

<!-- [dif] Difino estas la frazo difinanta la vorton, sencon aŭ
subsencon. Ĝi povas esti ankaŭ en alia(j) lingvo(j) ol la vorto
mem. La lingvon indikas la atributo <dfn>lng</dfn>.
-->

<!ELEMENT dif (#PCDATA|trd|trdgrp|ref|refgrp|ekz|snc|%tekst-stiloj;)*>
<!ATTLIST dif
	lng CDATA #IMPLIED
>

<!-- [ekz] Ekzemplo konsistas el ekzemplofrazo,
klarigoj kaj fonto.
-->

<!ELEMENT ekz (#PCDATA|fnt|uzo|ref|refgrp|ind|trd|trdgrp|%tekst-stiloj;)*>
<!ATTLIST ekz
	mrk ID #IMPLIED
>

<!-- [rim] Rimarko povas enhavi iujn indikojn pri la vorto aŭ
senco, krome referencojn, ekzemplojn, emfazitajn partojn.
-->
<!ELEMENT rim (#PCDATA|ref|refgrp|ekz|aut|fnt|%tekst-stiloj;)*>
<!ATTLIST rim
        num CDATA #IMPLIED
	mrk ID #IMPLIED
> 

<!-- [refgrp] Referencgrupo grupigas plurajn samtipajn
referencojn. La tipon indikas la atributo <dfn>tip</dfn>.
Tiukaze ne uzu la atributon <dfn>tip</dfn> en la subelementoj
<dfn>ref</dfn>!
-->

<!ELEMENT refgrp (#PCDATA|ref)*>
<!ATTLIST refgrp
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) "vid"
>

<!-- [ref] Referenco montras al alia, simil- aŭ alisignifa vorto,
oni povas distingi diversajn rilattipon al la
referencita vorto. La enhavo de la referenco estas tio, kio
aperas en la legebla teksto. La referencitan vorton mem
oni difinas per la atributo "cel". La celon oni plej
bone difinas per: radiko.derivaĵo.difino, oni povas uzi
la numeron de la difino au derivaĵo. Plej bone oni
generas la markojn (t.e. la eblaj celoj de referenco)
aŭtomate por minimumigi erarojn.
La atributoj "lst" kaj "val" servas por referenci al vortlisto (tip="lst"),
ekz. monatoj. Se temas pri ordigita listo, vi povas indiki valoron per "val",
ekz. "3" che la monato marto.
-->

<!ELEMENT ref (#PCDATA|tld|klr|sncref)*>
<!ATTLIST ref
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) #IMPLIED
	cel CDATA #REQUIRED
        lst CDATA #IMPLIED
	val CDATA #IMPLIED
>

<!-- [tez] NE PLU UZU! Tezaŭra nodo. Ĝi permesas referenci al tio, same kiel
 al kap kaj mem povas referenci al alia nodo.
-->
<!ELEMENT tez (#PCDATA|tld|klr|ref|refgrp)*>
<!ATTLIST tez
        mrk CDATA #REQUIRED
        tip (super|malprt|listo) #IMPLIED
	cel CDATA #REQUIRED
>

<!-- [lstref] Referenco al vortlisto el artikolo.
-->
<!ELEMENT lstref (#PCDATA|tld|klr)*>
<!ATTLIST lstref
        lst CDATA #REQUIRED
>

<!-- [tezrad] Tezaŭraradiko. La kapvorto aperas en la enir-listo
de la tezaŭro. Se vi uzas la atributon fak, ĝi aperas en la 
struktura enirlisto de la fako -->
<!ELEMENT tezrad EMPTY>
<!ATTLIST tezrad
        fak CDATA #IMPLIED
>

<!-- [trdgrp] Tradukgrupo kunigas diversajn tradukojn de
sama lingvo.
-->
<!ELEMENT trdgrp (#PCDATA|trd)*>
<!ATTLIST trdgrp
	lng CDATA #REQUIRED
>

<!-- [trd] Traduko kosistas el traduka vorto aŭ frazo
kaj klarigoj, poste povos sekvi aliaj elementoj.
-->
<!ELEMENT trd (#PCDATA|klr|ind|mll|ofc)*>
<!ATTLIST trd
	lng CDATA #IMPLIED
>

<!-- [ind] Parto de traduko, kiu liveras la kapvorton en la
indekso, do &lt;trd&gt;sich &lt;ind&gt;bem&uuml;hen&lt;/ind&gt;&lt;/trd&gt;
aperas sub bem&uuml;hen. Aŭ parto de ekzemplo aŭ bildpriskribo, al
kiu rilatas internaj tradukoj ktp.
-->
<!ELEMENT ind (#PCDATA|tld|klr|mll)*>

<!ELEMENT mll (#PCDATA|tld|klr|ind)*>
<!ATTLIST mll
        tip (kom|mez|fin) #IMPLIED
>

<!-- [bld] Bildo povas ilustri iun vorton aŭ sencon. Per la
atributo <dfn>lok</dfn> ĝi
referencas al ekstera dosiero, kiu entenas la bildon.
Per <dfn>alt</dfn> kaj <dfn>lrg</dfn> vi povas doni fiksan formaton.
Per <dfn>tip</dfn> vi donas tipon de la bildo, t.e. <dfn>img</dfn>
por JPEG, GIF, PNG-bildo, <dfn>svg</dfn> por SVG-vektorgrafiko.
-->
<!ELEMENT bld (#PCDATA|tld|klr|fnt|ind|trd|trdgrp)*>
<!ATTLIST bld
	lok CDATA #REQUIRED
	mrk ID #IMPLIED
	tip (img|svg) "img"
	alt CDATA #IMPLIED 
	lrg CDATA #IMPLIED
>

<!-- [adm] Administraj informoj estu por redaktado. Ili povus
enhavi informojn pri kreodato, ŝanĝdato, aŭtoro, eraroj kaj
plibonigproponoj pri artikolo. Ĝia strukturo ankoraŭ estas
diskutatebla.
-->
<!ELEMENT adm (#PCDATA|aut)*>

<!-- [tld] Tildo rilatas al la radiko, donita en la kapvorto
ĝi ne bezonas enhavon. La atributo <dfn>lit</dfn> indikas alian
komencliteron ol havas la radiko. Grava por majuskligo kaj
minuskligo.
-->
<!ELEMENT tld EMPTY>
<!ATTLIST tld
            lit CDATA #IMPLIED>       

<!-- [klr] Klarigo pri vorto, difino, ekzemplo ktp.-->
<!ELEMENT klr (#PCDATA|trd|trdgrp|ekz|ref|refgrp|%tekst-stiloj;)*>
<!ATTLIST klr
            tip (ind|amb) #IMPLIED>

<!-- [bib] Bibliografia indiko por fonto, estas mallongigo el
listo de difinitaj bibliografieroj kaj anstataŭas verko- kaj aŭtoroindikon
en la fontoj.
-->
<!ELEMENT bib (#PCDATA)*>

<!-- [vrk] Verko, en kiu troviĝas citita frazo aŭ vorto -->
<!ELEMENT vrk (#PCDATA|url)*>

<!-- [lok] Loko, kie troviĝas citita frazo aŭ vorto en verko -->
<!ELEMENT lok (#PCDATA|url)*>

<!-- [aut] Aŭtoro de citita frazo aŭ verko -->
<!ELEMENT aut (#PCDATA)>

<!-- [frm] Matematika au kemia formulo -->
<!ELEMENT frm (#PCDATA|sup|sub|g|k)*>

<!-- [g] Grasa parto de formulo, ekz. vektoro, matrico k.s.,
  bv. uzi nur en frm -->
<!ELEMENT g (#PCDATA)*>

<!-- [k] Kursiva parto de formulo, ekz. variablo k.s.,
  bv. uzi nur en frm -->
<!ELEMENT k (#PCDATA)*>

<!-- [em] Emfazo. Normale grase skribata vortoj.-->
<!ELEMENT em (#PCDATA|tld)*>

<!-- [sup] altigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sup (#PCDATA|g|k)*>

<!-- [sub] malaltigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sub (#PCDATA|g|k)*>

<!-- [ctl] citilita teksto, ekz. memindika uzo de vorto -->
<!ELEMENT ctl (#PCDATA|tld|em|frm)*>

<!-- [url] Referenco al iu ekstera dosiero. En la HTML-versio de vortaro
tio fariĝas &lt;a href=...&gt; Anstataŭ la TTT-ejo prefere uzu
la alinomojn difinitajn en la DTD, ĉar alikaze la referencoj tro
ofte malvalidiĝus. -->

<!ELEMENT url (#PCDATA)>
<!ATTLIST url 
          ref CDATA #IMPLIED>

<!-- [mlg] mallongigo de la kapvorto, ekz. che nomoj de organizajhoj. 
Per "kod" vi povas indiki devenon de la mallongigo, ekz. ISO-3166 ĉe landokodoj -->

<!ELEMENT mlg (#PCDATA)>
<!ATTLIST mlg
          kod CDATA #IMPLIED>




<!-- *************************************************
                   LITEROJ
******************************************************
-->

<!ENTITY % signoj SYSTEM "../dtd/vokosgn.dtd">
%signoj;

<!-- ************************************************
                   MALLONGIGOJ
*****************************************************
-->

<!ENTITY % mallongigoj SYSTEM "../dtd/vokomll.dtd">
%mallongigoj;

<!-- *************************************************
                   URLoj
******************************************************
-->

<!ENTITY % urloj SYSTEM "../dtd/vokourl.dtd">
%urloj;

=== sstangl/tuja-vortaro/revo/src/xml/smirg.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: smirg.xml,v 1.14 2015/07/04 08:37:43 revo Exp $">
<kap>
  <rad>smirg</rad>/o <fnt>Z</fnt> <fnt><bib>PV</bib></fnt>
</kap>
<drv mrk="smirg.0o">
  <kap><tld/>o</kap>
  <snc mrk="smirg.0o.MIN">
    <uzo tip="fak">MIN</uzo>
    <uzo tip="fak">TEK</uzo>
    <dif>
      Nepura korundo miksita kun kvarco kaj aliaj mineraloj kaj kies
      pulvoro estas uzata por glatigi a&ubreve; poluri metalojn, a&ubreve; malpoluri
      la
      vitron.
    </dif>
  </snc>
  <trd lng="be">&c_n;&c_a;&c_zh;&c_d;&c_a;&c_k;</trd>
  <trd lng="cs">smirek</trd>
  <trd lng="de">Schmirgel</trd>
  <trd lng="en">emery</trd>
  <trd lng="fa">&a_s;&a_n;&a_b;&a_A;&a_d;&a_h;</trd>
  <trd lng="fr">&eacute;meri</trd>
  <trd lng="hu">smirgel</trd>
  <trd lng="nl">amaril</trd>
  <trd lng="ru">&c_n;&c_a;&c_zh;&c_d;&c_a;&c_k;</trd>
  <trd lng="sk">šmirgeľ</trd>
</drv>

<drv mrk="smirg.0i">
  <kap><tld/>i</kap>
  <gra><vspec>tr</vspec></gra>
  <snc mrk="smirg.0i.TEK">
    <dif>
      Poluri, glatigi a&ubreve; malpoluri per <tld/>o.
    </dif>
  </snc>
  <trdgrp lng="cs">
    <trd>brousit smirkem</trd>,
    <trd>leštit smirkem</trd>,
    <trd>smirkovat</trd>
  </trdgrp>
  <trd lng="de">schmirgeln</trd>
  <trdgrp lng="en">
    <trd>grind with emery</trd>,
    <trd>polish with emery</trd>,
    <trd>rub with emery</trd>
  </trdgrp>
  <trd lng="fa">&a_s;&a_n;&a_b;&a_A;&a_d;&a_h; &a_z;&a_d;&a_n;</trd>
  <trd lng="fr">abraser</trd>
  <trdgrp lng="hu">
    <trd>csiszol <klr tip="ind">(smirglivel)</klr></trd>,
    <trd>smirgliz</trd>
  </trdgrp>
  <trd lng="nl">gladschuren</trd>
  <trd lng="ru">&c_z;&c_a;&c_ch;&c_i;&c_shch;&c_a;&c_t;&c_mol; <ind>&c_n;&c_a;&c_zh;&c_d;&c_a;&c_k;&c_o;&c_m;</ind></trd>
  <trd lng="sk">šmirgľovať</trd>
</drv>
</art>
<!--
$Log: smirg.xml,v $
Revision 1.14  2015/07/04 08:37:43  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.13  2015/06/29 16:33:23  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.12  2010/04/15 16:30:22  revo
Behnam Tabatabai: +trd fa

Revision 1.11  2009/10/08 16:30:46  revo
Russ Williams: +trd en

Revision 1.10  2009/05/17 16:31:53  revo
Jeromo Vasxe: - ~opapero portita al art. paper

Revision 1.9  2007/08/05 16:31:37  revo
Jeromo Vasxe: + mrk + 1 ekz + trd fr

Revision 1.8 2004/10/18 16:32:43 revo
Jozefo Horvath: +trd hu

Revision 1.7 2003/01/17 17:32:57 revo
Zmicier Lapcionak: + trd be

Revision 1.6 2002/02/13 17:33:49 revo
Yury Finkel: korindo->korundo, +trd ru

Revision 1.5 2001/09/30 19:10:28 revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/vermicxel.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: vermicxel.xml,v 1.9 2013/08/01 09:10:10 revo Exp $">
<kap>
  <ofc>*</ofc>
  <rad>vermi&ccirc;el</rad>/o <fnt><bib>PV</bib></fnt>
</kap>
<drv mrk="vermicxel.0o">
  <kap><ofc>*</ofc><tld/>o</kap>
  <uzo tip="fak">KUI</uzo>
  <snc mrk="vermicxel.0o.vermforma">
    <dif>
      Fadenforma <ref tip="super" cel="nudel.0o">nudelo</ref>:
      <ekz>
        &ccirc;iu el ni man&gcirc;is tason da fritita <tld/>o
        <fnt>
          <aut>Hasegawa T.</aut>,
          <vrk><url
          ref="http://wikilivres.ca/wiki/En_%C4%88inio_Batalanta">
          En &Ccirc;inio Batalanta</url></vrk>, 
          <lok>1954</lok>
        </fnt>.
      </ekz>
    </dif>
    <trd lng="hu">c&eacute;rnamet&eacute;lt</trd>
    <trd lng="ru">&c_v;&c_je;&c_r;&c_m;&c_i;&c_sh;&c_je;&c_l;&c_mol;</trd>
  </snc>
  <snc mrk="vermicxel.0o.cxia">
    <dif>
      &Ccirc;ia <ref tip="sin" cel="nudel.0o.cxia">nudelo</ref>,
      <ref tip="sin" cel="past.0ajxo.nudelo">pasta&jcirc;o</ref>
      preparata per bolkuirado.
    </dif>
    <rim mrk="vermicxel.0o.rimFund">
      El la tradukoj germanen, rusen kaj polen, kiujn donas UV,
      evidentas ke la intenco estis doni al la vorto la sencon
      &gcirc;eneralan (tiun de <tld/>o<sncref ref="vermicxel.0o.cxia"/>).
      Tamen la nunaj vortaroj &ccirc;i tiun fundamentan sencon e&ccirc;
      ne mencias.
    </rim>
    <trd lng="hu">met&eacute;lt <ind>t&eacute;szta</ind></trd>
    <trd lng="pl">makaron</trd>
    <trdgrp lng="ru">
      <trd>&c_m;&c_a;&c_k;&c_a;&c_r;&c_o;&c_n;&c_n;&c_o;&c_je; &c_i;&c_z;&c_d;&c_je;&c_l;&c_i;&c_je;</trd>,
      <trd>&c_l;&c_a;&c_p;&c_sh;&c_a;</trd>
    </trdgrp>
  </snc>
  <rim mrk="vermicxel.0o.nombro">
    En la PIV-oj la vorto indikas unuopan peceton de la pasta&jcirc;o,
    en UV la vorto havas sencon aran.
  </rim>
  <trd lng="be">&c_v;&c_e;&c_r;&c_m;&c_ib;&c_sh;&c_e;&c_l;&c_mol;</trd>
  <trd lng="bg">&c_f;&c_i;&c_d;&c_je;</trd>
  <trd lng="ca">fideu</trd>
  <trd lng="de">Fadennudeln</trd>
  <trd lng="es">fideo</trd>
  <trd lng="fr">vermicelle</trd>
  <trd lng="en">vermicelli</trd>
  <trd lng="nl">vermicelli</trd>
  <trdgrp lng="pt">
   <trd>aletria</trd>,
   <trd>letria</trd>,
   <trd>cabelo-de-anjo</trd>,
   <trd>fidelinho</trd>,
   <trd>fid&eacute;u</trd>
  </trdgrp>
</drv>
</art>
<!--
$Log: vermicxel.xml,v $
Revision 1.9  2013/08/01 09:10:10  revo
Joop Eggen: +trd bg

Revision 1.8  2012/09/19 10:10:08  revo
Jeromo Vasxe: + ekz

Revision 1.7  2012/08/12 10:10:18  revo
Marc Rausell: + trd ca

Revision 1.6  2008/07/16 16:30:54  revo
Jozefo Horvath: +trd hu

Revision 1.5  2006/02/02 17:31:40  revo
Tulio Flores: +trd pt

Revision 1.4  2005/12/17 17:31:30  revo
Jeromo Vasxe: kor 1 mrk

Revision 1.3 2005/12/06 17:33:29 revo
Raul Salinas Monteagudo: +trd es

Revision 1.2 2004/06/08 21:25:08 revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/galant.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: galant.xml,v 1.21 2015/07/04 08:37:34 revo Exp $">
<kap><ofc>2</ofc>
<rad>galant</rad>/o</kap>
<drv mrk="galant.0o">
  <kap><tld/>o</kap>
  <uzo tip="fak">BOT</uzo>
  <snc>
    <dif>
      <ref tip="lst" cel="genr.0o.BIO"
      lst="voko:botanikaj_genroj">Genro</ref> el familio <ref
      tip="malprt"
      cel="amaril1.0oj">amarilidacoj</ref>
      (<trd lng="la">Galanthus</trd>),
      floranta en la fino de la vintro,
      kun malgrandaj blankaj sonorilformaj floroj el
      du rondoj de petaloj, tri eksteraj, ovalaj kaj pure
      blankaj, kaj tri internaj kunklinitaj kiel kroneto kun
      verdaj makuloj &ccirc;e la pintoj.
    </dif>
  </snc>
  <bld lok="../bld/galant.jpg">
    <tld/>oj
  </bld>
  <trdgrp lng="ca">
    <trd>g&egrave;nere Galanthus</trd>,
    <trd>lliri de neu</trd>
  </trdgrp>
  <trd lng="de">Schneegl&ouml;ckchen</trd>
  <trd lng="fr">perce-neige</trd>
  <trd lng="hu">h&oacute;vir&aacute;g</trd>
  <trd lng="nl">sneeuwklokje</trd>
  <trdgrp lng="pt">
   <trd>galanto</trd>, 
   <trd>fura-neve</trd>, 
   <trd>cip&oacute;-da-praia</trd>,
   <trd>campainha-branca</trd>,
   <trd>salsa-da-praia</trd>
  </trdgrp>
  <trd lng="ru">&c_p;&c_o;&c_d;&c_s;&c_n;&c_je;&c_zh;&c_n;&c_i;&c_k;</trd>
  <trd lng="sv">sn&ouml;droppe</trd>
  <trd lng="tr">kardelen</trd>
  <trd lng="sk">snežienka</trd>
  <trd lng="cs">sněženka</trd>
</drv>
</art>
<!--
$Log: galant.xml,v $
Revision 1.21  2015/07/04 08:37:34  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.20  2015/06/29 16:29:39  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.19  2013/08/26 08:10:21  revo
Wolfram Diestel: referenco al listo bot genroj

Revision 1.18  2011/12/11 21:10:24  revo
Marc Rausell: +trd ca

Revision 1.17  2009/08/23 16:33:08  revo
Emmanuel Debanne: +trd tr

Revision 1.16  2005/08/15 16:31:45  revo
Luiz Portella: +trd pt

Revision 1.15  2004/10/17 16:32:10  revo
Wolfram Diestel: kor. germ trd

Revision 1.14  2002/03/27 17:32:00  revo
Jozefo Horvath: +trd hu

Revision 1.13  2002/03/01 21:30:44  revo
Wolfram Diestel: alia bildo, precizigis dif

Revision 1.12  2001/12/11 18:22:48  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/anticiklon.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: anticiklon.xml,v 1.3 2015/07/04 08:37:30 revo Exp $">
<kap>
  <rad>anticiklon</rad>/o <fnt><bib>PIV1</bib></fnt>
</kap>
<drv mrk="anticiklon.0o">
  <kap><tld/>o</kap>
  <snc mrk="anticiklon.0o.MET">
    <uzo tip="fak">MET</uzo>
    <ref tip="dif" cel="ciklon.kontraux0o.MET">kontra&ubreve;ciklono</ref>
    <ekz>
      somere la <tld/>o alportas varmegan, preska&ubreve; sennuban
      veteron; vintre &gcirc;i karakterizi&gcirc;as per frosta vetero
      kaj nebuloj
      <fnt>
        <aut>E. Alvim de Oliveira</aut>,
        <vrk>Meteologio: bazaj principoj pri vetero kaj klimato</vrk>,
        <lok>en: 4a Kongreso de Esperanto de &Scirc;tato San-Pa&ubreve;lo, 2009</lok>
      </fnt>.
      </ekz>
  </snc>
  <trdgrp lng="cs">
    <trd>anticyklona</trd>,
    <trd>tlaková výše</trd>
  </trdgrp>
  <trd lng="fr">anticyclone</trd>
  <trd lng="sk">anticyklón</trd>
</drv>
</art>

<!--
$Log: anticiklon.xml,v $
Revision 1.3  2015/07/04 08:37:30  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.2  2015/06/28 12:03:35  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.1  2012/04/23 09:10:11  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/latvi.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: latvi.xml,v 1.10 2015/07/04 08:37:38 revo Exp $">
<kap>
  <rad>Latvi</rad>/o
</kap>

<drv mrk="latvi.L0o">
  <kap><tld/>o</kap>
  <snc>
  <uzo tip="fak">GEOG</uzo>
  <uzo tip="fak">POL</uzo>
    <ref tip="dif" cel="latv.L0ujo.GEOG">Latvujo</ref>
      <ekz>
        <tld lit="L"/>o estas lando en nordoriento de E&ubreve;ropo.
        <fnt><bib>Viki</bib>, <lok><url 
        ref="http://eo.wikipedia.org/wiki/Latvio">Latvio</url></lok></fnt>.
      </ekz>
  </snc>
  <trd lng="bg">&c_L;&c_a;&c_t;&c_v;&c_i;&c_ja;</trd>
  <trd lng="cs">Lotyšsko</trd>
  <trd lng="de">Lettland</trd>
  <trd lng="en">Latvia</trd>
  <trd lng="fr">Lettonie</trd>
  <trd lng="hu">Lettorsz&aacute;g</trd>
  <trd lng="id">Latvia</trd>
  <trd lng="nl">Letland</trd>
  <trd lng="pl">&Lstroke;otwa</trd>
  <trd lng="sk">Lotyšsko</trd>
</drv>
</art>

<!--
$Log: latvi.xml,v $
Revision 1.10  2015/07/04 08:37:38  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.9  2015/06/29 16:33:19  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.8  2014/06/04 04:10:41  revo
Eko Nur Syah Hidayat: +id

Revision 1.7  2014/04/14 12:10:29  revo
Damien Brucker: +trd fr

Revision 1.6  2011/02/15 16:10:26  revo
Luiz Portella: kor. ref k mrk

Revision 1.5  2009/07/05 16:39:59  revo
Paul Peeraerts: +trd nl

Revision 1.4  2009/04/29 16:32:02  revo
Sebastian Cyprych: +trd pl

Revision 1.3  2008/12/19 17:30:24  revo
Luiz Portella: kor mrk; -mrk dif; +ref dif

Revision 1.2  2008/07/21 16:30:37  revo
Jozefo Horvath: +trd hu

Revision 1.1  2008/02/01 17:30:26  revo
-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/pug.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: pug.xml,v 1.17 2015/07/04 08:37:42 revo Exp $">
<kap>
  <rad>pug</rad>/o
</kap>
<drv mrk="pug.0o">
  <kap><tld/>o</kap>
  <snc>
    <dif>
      La du <ref tip="prt" cel="vang.sid0o">sidvangoj</ref> &ccirc;e homo:
      <ekz>
        la <ind>bel<tld/>a</ind> Afrodita <klr>(fama helena
        statuo)</klr>;
        <trd lng="fr">callipyge</trd>
      </ekz>
      <ekz>
        <ind><tld/>mezuro</ind> <klr>(por al&gcirc;ustigo de jupo a&ubreve;
        de pantalono)</klr>;
        <trd lng="fr">tour de hanches</trd>
      </ekz>
      <ekz>
        unu supra&jcirc;a rigardo sur lian viza&gcirc;on sufi&ccirc;as
        por kompreni, ke li estas malnobla, &ccirc;ikanema, senprincipa,
        <ind><tld/>olekema</ind> kanajlo <klr>(flatemulo)</klr>
        <fnt><bib>MkM</bib><lok>&ccirc;ap. 7</lok></fnt>.
        <trd lng="fr">l&egrave;che-cul<klr tip="ind"> (adj.)</klr></trd>
      </ekz>
    </dif>
    <ref tip="vid" cel="post.0ajxo.pugo">posta&jcirc;o</ref>
  </snc>
  <trd lng="be">&c_z;&c_a;&c_d;&c_n;&c_ib;&c_c;&c_a;</trd>
  <trd lng="bg">&c_d;&c_u;&c_p;&c_je;</trd>
  <trdgrp lng="cs">
    <trd>boky</trd>,
    <trd>zadek</trd>,
    <trd>zadnice</trd>,
    <trd>zvířecí řiť</trd>
  </trdgrp>
  <trdgrp lng="de">
    <trd>Hintern</trd>,
    <trd>Arsch</trd>,
    <trd>Popo</trd>,
    <trd>Po</trd>
  </trdgrp>
  <trdgrp lng="en">
    <trd>buttocks</trd>,
    <trd>rump</trd>,
    <trd>backside</trd>,
    <trd>cheeks</trd>,
    <trd>butt</trd>,
    <trd>ass</trd>
  </trdgrp>
  <trdgrp lng="es">
    <trd>trasero</trd>,
    <trd>nalgas</trd>,
    <trd>culo</trd>
  </trdgrp>
  <trdgrp lng="fr">
    <trd>derri&egrave;re<klr tip="ind"> (ana.)</klr></trd>,
    <trd>post&eacute;rieur<klr tip="ind"> (ana.)</klr></trd>,
    <trd>cul</trd>
  </trdgrp>
  <trdgrp lng="hu">
    <trd>far</trd>,
    <trd>h&aacute;ts&oacute;</trd>,
    <trd>fen&eacute;k</trd>
  </trdgrp>
  <trdgrp lng="it">
    <trd>sedere</trd>,
    <trd>culo</trd>,
    <trd>didietro</trd>
  </trdgrp>
  <trd lng="nl">achterwerk</trd>
  <trdgrp lng="pl">
    <trd>po&sacute;ladki</trd>,
    <trd>okolica <ind>po&sacute;ladkowa</ind></trd>,
    <trd>zad</trd>,
    <trd>zadek</trd>,
    <trd>ty&lstroke;ek</trd>,
    <trd>siedzenie</trd>,
    <trd>pupa <klr>(euf.)</klr></trd>,
    <trd>dupa <klr>(wulg.)</klr></trd>
  </trdgrp>
  <trdgrp lng="pt">
    <trd>n&aacute;degas</trd>,  
    <trd>bunda</trd>
  </trdgrp>
  <trd lng="ru">&c_z;&c_a;&c_d;&c_n;&c_i;&c_c;&c_a;</trd>
  <trd lng="sk">zadok</trd>
</drv>
</art>
<!--
$Log: pug.xml,v $
Revision 1.17  2015/07/04 08:37:42  revo
aldono de trd cs per skripto de M. von Laer

Revision 1.16  2015/06/29 16:40:19  revo
aldono de trd sk per skripto de M. von Laer

Revision 1.15  2013/07/10 15:10:08  revo
Joop Eggen: +trd bg

Revision 1.14  2010/01/18 17:31:58  revo
Russ Williams: +trd en

Revision 1.13  2009/03/06 17:30:47  revo
Marcus Curdeius: +pl

Revision 1.12  2006/04/17 16:32:27  revo
Tulio Flores: +tr pt

Revision 1.11  2004/02/22 17:32:13  revo
Marc Bavant: mod dif, +trd en ekz, +ekz kun ~olekema, mod ref tip al
postajxo, mod trd fr

Revision 1.10 2003/07/26 08:43:48 revo
Dmitri Gabinski: +trd be

Revision 1.9 2003/01/29 17:32:33 revo
Marco Trevisan Herraz: +trd it

-->
</vortaro>

=== sstangl/tuja-vortaro/revo/src/xml/empiri2.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: empiri2.xml,v 1.6 2014/11/26 13:10:23 revo Exp $">
  <kap>
    <rad>empirist</rad>/o
    <fnt>Z</fnt>
  </kap>
  <drv mrk="empiri2.0o">
  <kap><tld/>o</kap>
  <snc>
      <ref tip="dif" cel="empiri.0isto">empiriisto</ref>  
  </snc>
  <trd lng="be">&c_e;&c_m;&c_p;&c_ib;&c_r;&c_y;&c_k;</trd>
  <trd lng="fr">empiriste</trd>
  <trdgrp lng="ru">
    <trd>&c_e;&c_m;&c_p;&c_i;&c_r;&c_i;&c_k;</trd>,
    <trd>&c_p;&c_r;&c_a;&c_k;&c_t;&c_i;&c_k;</trd>
  </trdgrp>
  </drv>
</art>
<!--
$Log: empiri2.xml,v $
Revision 1.6  2014/11/26 13:10:23  revo
Damien Brucker: +trd fr

Revision 1.5  2003/12/17 17:31:08  revo
Dmitri Gabinski: +trd be

Revision 1.4  2001/04/11 16:21:15  revo
Yury Finkel: +trd ru

-->
</vortaro>
